// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package talos

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"slices"
	"time"

	"github.com/cosi-project/runtime/pkg/safe"
	"github.com/spf13/cobra"
	"golang.org/x/term"

	"github.com/siderolabs/talos/cmd/talosctl/pkg/talos/global"
	"github.com/siderolabs/talos/cmd/talosctl/pkg/talos/safeout"
	"github.com/siderolabs/talos/pkg/machinery/client"
	"github.com/siderolabs/talos/pkg/machinery/client/multiplex"
	"github.com/siderolabs/talos/pkg/machinery/resources/block"
)

var recoveryKeyCmdFlags struct {
	global.InsecureFlags

	volumes []string
	keyFile string
	timeout time.Duration
}

var recoveryKeyCmd = &cobra.Command{
	Use:   "recovery-key",
	Short: "Manage disk encryption recovery keys",
	Long: `Manage disk encryption recovery keys.

A recovery key is a disk encryption key which is held by the operator and never stored on the node:
the key slot is reserved in the machine configuration ('recovery: {}' in the volume encryption keys).
The node generates the key when it enrolls the slot, and keeps it in memory until it is fetched once
with 'talosctl recovery-key fetch'. Until the key is fetched, it is regenerated on every boot.

The key is used to unlock a volume which can't be unlocked with any of the automatic keys
(e.g. after a TPM state change), from the console dashboard or with 'talosctl recovery-key unlock'.

For 'unlock' and 'verify', the recovery key is read from the file passed via --key-file
('-' for stdin), or prompted for on the terminal.`,
	Args: cobra.NoArgs,
}

var recoveryKeyFetchCmd = &cobra.Command{
	Use:   "fetch",
	Short: "Fetch the recovery keys generated by the nodes",
	Long: `Fetch the recovery keys generated by the nodes.

Each key is printed once and then dropped by the node: store it in a safe place, it can't be recovered
from the node afterwards. Use 'talosctl recovery-key verify' to check the stored key.`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, _ []string) error {
		ctx := cmd.Context()

		clientFactory, err := NewClientFactory(ctx, &recoveryKeyCmdFlags)
		if err != nil {
			return err
		}

		defer clientFactory.Close() //nolint:errcheck

		respCh := multiplex.UnaryViaFactory(
			ctx, clientFactory,
			func(ctx context.Context, c *client.Client) ([]string, error) {
				resp, err := c.EncryptionRecoveryKeyFetch(ctx, recoveryKeyCmdFlags.volumes)
				if err != nil {
					return nil, err
				}

				var lines []string

				for _, msg := range resp.GetMessages() {
					for _, result := range msg.GetResults() {
						lines = append(lines, fmt.Sprintf("%s: %s", result.GetVolume(), string(result.GetKey())))
					}
				}

				return lines, nil
			},
		)

		var errs error

		for resp := range respCh {
			if resp.Err != nil {
				errs = errors.Join(errs, fmt.Errorf("node %s: %w", resp.Node, resp.Err))

				continue
			}

			for _, line := range resp.Payload {
				safeout.Fprintf(cmd.OutOrStdout(), "%s: %s\n", resp.Node, line) //nolint:errcheck
			}
		}

		if errs == nil {
			fmt.Fprintln(safeout.Stderr(), "Store the recovery keys in a safe place: the nodes have dropped them.")
		}

		return errs
	},
}

var recoveryKeyUnlockCmd = &cobra.Command{
	Use:   "unlock",
	Short: "Unlock the locked volumes with the recovery key",
	Long: `Unlock the locked volumes with the recovery key.

A volume is locked when it can't be unlocked with any of the automatic keys (TPM, KMS, ...) while a
recovery key is configured. The automatic keys keep being retried in the background; once the volume
is unlocked with the recovery key, the failed automatic keys are re-enrolled.

This command applies to volumes other than STATE (EPHEMERAL, user and raw volumes), e.g. volumes
which use a KMS that is unreachable while STATE is unlocked by another key. The Talos API is not
available while STATE itself is locked: unlock STATE from the console dashboard.`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, _ []string) error {
		key, err := readRecoveryKey(cmd)
		if err != nil {
			return err
		}

		return supplyRecoveryKey(cmd.Context(), key, recoveryKeyCmdFlags.volumes, func(volumeStatus *block.VolumeStatus) (bool, string) {
			spec := volumeStatus.TypedSpec()

			switch spec.Phase { //nolint:exhaustive
			case block.VolumePhaseLocked:
				return false, "volume is locked: " + spec.ErrorMessage
			case block.VolumePhaseFailed:
				return false, "volume failed: " + spec.ErrorMessage
			case block.VolumePhasePrepared, block.VolumePhaseReady:
				return true, "volume unlocked"
			default:
				return false, "volume phase is " + spec.Phase.String()
			}
		})
	},
}

var recoveryKeyVerifyCmd = &cobra.Command{
	Use:   "verify",
	Short: "Verify the recovery key against the volumes",
	Long: `Verify the recovery key against the recovery key slot of the volumes.

Nothing is changed on the node. The command fails if the key doesn't match any of the volumes.`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, _ []string) error {
		key, err := readRecoveryKey(cmd)
		if err != nil {
			return err
		}

		ctx := cmd.Context()

		clientFactory, err := NewClientFactory(ctx, &recoveryKeyCmdFlags)
		if err != nil {
			return err
		}

		defer clientFactory.Close() //nolint:errcheck

		respCh := multiplex.UnaryViaFactory(
			ctx, clientFactory,
			func(ctx context.Context, c *client.Client) ([]string, error) {
				resp, err := c.EncryptionRecoveryKeyVerify(ctx, recoveryKeyCmdFlags.volumes, key)
				if err != nil {
					return nil, err
				}

				var lines []string

				for _, msg := range resp.GetMessages() {
					for _, result := range msg.GetResults() {
						if result.GetValid() {
							lines = append(lines, fmt.Sprintf("%s: recovery key is valid", result.GetVolume()))
						} else {
							lines = append(lines, fmt.Sprintf("%s: recovery key is INVALID", result.GetVolume()))

							err = errors.Join(err, fmt.Errorf("recovery key is invalid for volume %s", result.GetVolume()))
						}
					}
				}

				return lines, err
			},
		)

		var errs error

		for resp := range respCh {
			for _, line := range resp.Payload {
				safeout.Fprintf(cmd.OutOrStdout(), "%s: %s\n", resp.Node, line) //nolint:errcheck
			}

			if resp.Err != nil {
				errs = errors.Join(errs, fmt.Errorf("node %s: %w", resp.Node, resp.Err))
			}
		}

		return errs
	},
}

// supplyRecoveryKey supplies the key to the nodes, and waits for each requested volume to reach the expected state.
func supplyRecoveryKey(ctx context.Context, key []byte, volumes []string, check func(*block.VolumeStatus) (bool, string)) error {
	clientFactory, err := NewClientFactory(ctx, &recoveryKeyCmdFlags)
	if err != nil {
		return err
	}

	defer clientFactory.Close() //nolint:errcheck

	respCh := multiplex.UnaryViaFactory(
		ctx, clientFactory,
		func(ctx context.Context, c *client.Client) ([]string, error) {
			resp, err := c.EncryptionRecoveryKeySupply(ctx, volumes, key)
			if err != nil {
				return nil, err
			}

			var suppliedVolumes []string

			for _, msg := range resp.GetMessages() {
				suppliedVolumes = append(suppliedVolumes, msg.GetVolumes()...)
			}

			return waitForVolumes(ctx, c, suppliedVolumes, check)
		},
	)

	var errs error

	for resp := range respCh {
		for _, line := range resp.Payload {
			safeout.Fprintf(safeout.Stderr(), "%s: %s\n", resp.Node, line) //nolint:errcheck
		}

		if resp.Err != nil {
			errs = errors.Join(errs, fmt.Errorf("node %s: %w", resp.Node, resp.Err))
		}
	}

	return errs
}

// waitForVolumes polls the volume statuses until the check passes for every volume, or the timeout expires.
func waitForVolumes(ctx context.Context, c *client.Client, volumes []string, check func(*block.VolumeStatus) (bool, string)) ([]string, error) {
	ctx, cancel := context.WithTimeout(ctx, recoveryKeyCmdFlags.timeout)
	defer cancel()

	ticker := time.NewTicker(500 * time.Millisecond)
	defer ticker.Stop()

	pending := slices.Clone(volumes)
	lastStatus := map[string]string{}

	var lines []string

	for {
		for _, volumeID := range slices.Clone(pending) {
			volumeStatus, err := safe.StateGetByID[*block.VolumeStatus](ctx, c.COSI, volumeID)
			if err != nil {
				if ctx.Err() != nil {
					// timed out, report the last known state below
					break
				}

				return lines, fmt.Errorf("error getting volume status %q: %w", volumeID, err)
			}

			done, message := check(volumeStatus)
			lastStatus[volumeID] = message

			if done {
				lines = append(lines, fmt.Sprintf("%s: %s", volumeID, message))
				pending = slices.DeleteFunc(pending, func(id string) bool { return id == volumeID })
			}
		}

		if len(pending) == 0 {
			return lines, nil
		}

		select {
		case <-ctx.Done():
			var errs error

			for _, volumeID := range pending {
				errs = errors.Join(errs, fmt.Errorf("timed out waiting for volume %s: %s", volumeID, lastStatus[volumeID]))
			}

			return lines, errs
		case <-ticker.C:
		}
	}
}

// readRecoveryKey reads the recovery key from the key file, stdin, or prompts for it on the terminal.
func readRecoveryKey(cmd *cobra.Command) ([]byte, error) {
	var (
		key []byte
		err error
	)

	switch {
	case recoveryKeyCmdFlags.keyFile != "" && recoveryKeyCmdFlags.keyFile != "-":
		key, err = os.ReadFile(recoveryKeyCmdFlags.keyFile)
		if err != nil {
			return nil, fmt.Errorf("error reading recovery key file: %w", err)
		}
	case recoveryKeyCmdFlags.keyFile == "-" || !term.IsTerminal(int(os.Stdin.Fd())):
		key, err = io.ReadAll(cmd.InOrStdin())
		if err != nil {
			return nil, fmt.Errorf("error reading recovery key from stdin: %w", err)
		}
	default:
		fmt.Fprint(safeout.Stderr(), "Recovery key: ")

		key, err = term.ReadPassword(int(os.Stdin.Fd()))

		fmt.Fprintln(safeout.Stderr())

		if err != nil {
			return nil, fmt.Errorf("error reading recovery key: %w", err)
		}
	}

	key = bytes.TrimRight(key, "\r\n")

	if len(bytes.TrimSpace(key)) == 0 {
		return nil, errors.New("recovery key must not be empty")
	}

	return key, nil
}

func init() {
	recoveryKeyCmdFlags.InsecureFlags.AddPersistentFlags(recoveryKeyCmd)
	recoveryKeyCmd.PersistentFlags().StringSliceVar(&recoveryKeyCmdFlags.volumes, "volumes", nil, "volume IDs to operate on (default: all applicable volumes)")
	recoveryKeyCmd.PersistentFlags().StringVar(&recoveryKeyCmdFlags.keyFile, "key-file", "", "file to read the recovery key from ('-' for stdin); prompted for on the terminal if not set")
	recoveryKeyCmd.PersistentFlags().DurationVar(&recoveryKeyCmdFlags.timeout, "timeout", time.Minute, "time to wait for the volumes to be unlocked")

	recoveryKeyCmd.AddCommand(recoveryKeyFetchCmd)
	recoveryKeyCmd.AddCommand(recoveryKeyUnlockCmd)
	recoveryKeyCmd.AddCommand(recoveryKeyVerifyCmd)
	addCommand(recoveryKeyCmd)
}
