version: "2"
run:
  build-tags:
    - integration
    - integration_api
    - integration_cli
    - integration_k8s
    - integration_provision
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: false
linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - dupword
    - err113
    - errorlint
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godox
    - gosec
    - inamedparam
    - ireturn
    - maintidx
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - promlinter
    - protogetter
    - recvcheck
    - tagalign
    - tagliatelle
    - testifylint
    - thelper
    - varnamelen
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 20
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: true
      exclude-functions:
        - fmt.Fprintln
        - fmt.Fprintf
        - fmt.Fprint
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 10
    gomoddirectives:
      replace-allow-list:
        - gopkg.in/yaml.v3
        - github.com/coredns/coredns
        - github.com/mdlayher/kobject
        - golang.zx2c4.com/wireguard
        - golang.zx2c4.com/wireguard/wgctrl
        - cloud.google.com/go
        - github.com/mdlayher/ethtool
        - github.com/insomniacslk/dhcp
        - github.com/cosi-project/runtime
      replace-local: true
      exclude-forbidden: false
      retract-allow-no-explanation: false
    lll:
      line-length: 200
      tab-width: 1
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-QF1001", "-QF1008"]
    unused:
      local-variables-are-used: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: cmd/talosctl/cmd
      - linters:
          - dupl
        path: internal/app/machined/internal/phase
      - linters:
          - dupl
        path: internal/app/machined/pkg/system/services
      - linters:
          - revive
        path: cmd/talosctl/cmd/mgmt
        text: should have a package comment
      - linters:
          - revive
        path: cmd/talosctl/cmd/mgmt/inject
        text: should have a package comment
      - linters:
          - revive
        path: cmd/talosctl/cmd/talos
        text: should have a package comment
      - linters:
          - revive
        path: cmd/talosctl/pkg/talos/action
        text: should have a package comment
      - linters:
          - revive
        path: cmd/talosctl/pkg/talos/global
        text: should have a package comment
      - linters:
          - revive
        path: cmd/talosctl/pkg/talos/helpers
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/controllers/cri
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/controllers/kubeaccess/serviceaccount
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/controllers/perf
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/system/events
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/system/health
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/system/runner/containerd
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/system/runner/goroutine
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/system/runner/process
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/system/runner/restart
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/machined/pkg/system
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/maintenance
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/maintenance/server
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/poweroff
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/trustd/internal/reg
        text: should have a package comment
      - linters:
          - revive
        path: internal/app/trustd
        text: should have a package comment
      - linters:
          - revive
        path: internal/pkg/containers/image
        text: should have a package comment
      - linters:
          - revive
        path: internal/pkg/etcd
        text: should have a package comment
      - linters:
          - revive
        path: internal/pkg/install
        text: should have a package comment
      - linters:
          - revive
        path: internal/pkg/mount
        text: should have a package comment
      - linters:
          - revive
        path: internal/pkg/mount/switchroot
        text: should have a package comment
      - linters:
          - revive
        path: internal/pkg/tui/components
        text: should have a package comment
      - linters:
          - revive
        path: pkg/argsbuilder
        text: should have a package comment
      - linters:
          - revive
        path: pkg/chunker
        text: should have a package comment
      - linters:
          - revive
        path: pkg/chunker/file
        text: should have a package comment
      - linters:
          - revive
        path: pkg/chunker/stream
        text: should have a package comment
      - linters:
          - revive
        path: pkg/download
        text: should have a package comment
      - linters:
          - revive
        path: pkg/grpc/dialer
        text: should have a package comment
      - linters:
          - revive
        path: pkg/grpc/factory
        text: should have a package comment
      - linters:
          - revive
        path: pkg/grpc/gen
        text: should have a package comment
      - linters:
          - revive
        path: pkg/grpc/middleware/auth/basic
        text: should have a package comment
      - linters:
          - revive
        path: pkg/grpc/middleware/authz
        text: should have a package comment
      - linters:
          - revive
        path: pkg/kubernetes
        text: should have a package comment
      - linters:
          - revive
        path: pkg/kubernetes/inject
        text: should have a package comment
      - linters:
          - revive
        path: pkg/provision/providers
        text: should have a package comment
      - linters:
          - revive
        path: pkg/provision/providers/qemu
        text: should have a package comment
      - linters:
          - revive
        path: config/encoder
        text: should have a package comment
      - linters:
          - revive
        path: resources/kubespan
        text: should have a package comment
      - linters:
          - revive
        path: client/config
        text: should have a package comment
      - linters:
          - revive
        path: config/merge
        text: should have a package comment
      - linters:
          - revive
        path: config/types/v1alpha1/bundle
        text: should have a package comment
      - linters:
          - revive
        path: resources/cri
        text: should have a package comment
      - linters:
          - revive
        path: resources/runtime
        text: should have a package comment
      - linters:
          - revive
        path: kernel
        text: should have a package comment
      - linters:
          - revive
        path: constants
        text: should have a package comment
      - linters:
          - revive
        path: resources/perf
        text: should have a package comment
      - linters:
          - revive
        path: resources/cluster
        text: should have a package comment
      - linters:
          - revive
        path: role
        text: should have a package comment
      - linters:
          - revive
        path: resources/hardware
        text: should have a package comment
      - linters:
          - revive
        path: config/decoder
        text: should have a package comment
      - linters:
          - revive
        path: config/internal/cis
        text: should have a package comment
      - linters:
          - revive
        path: config/types/v1alpha1/machine
        text: should have a package comment
      - linters:
          - dupl
        path: config/types/v1alpha1
      - linters:
          - unused
        path: specs-go/config.go
      - path: (.+)\.go$
        text: package comment should be of the form "Package services ..."
      - path: (.+)\.go$
        text: ^ST1000
      - path: (.+)\.go$
        text: parameter '\w+' seems to be unused, consider removing or renaming it as _
    paths:
      - .*\\.pb\\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/siderolabs/talos)
  exclusions:
    generated: lax
    paths:
      - .*\\.pb\\.go$
      - third_party$
      - builtin$
      - examples$
