version = 2

disabled_plugins = [
    "io.containerd.v1.devmapper",
    "io.containerd.v1.zfs",
    "io.containerd.snapshotter.v1.aufs",
    "io.containerd.snapshotter.v1.btrfs",
    "io.containerd.snapshotter.v1.devmapper",
    "io.containerd.snapshotter.v1.zfs",
]

imports = ["/var/cri/conf.d/*.toml"]

[debug]
level = "info"
format = "json"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
runtime_type = "io.containerd.runc.v2"
