# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"
ignore_deps = ["github.com/coredns/coredns"]

# previous release
previous = "v1.13.0-rc.0"

pre_release = true

preface = """
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
Linux: 6.18.23
Kubernetes: 1.36.0

Talos is built with Go 1.26.2.
"""

    [notes.nts]
        title = "NTS for Time Synchronization"
        description = """\
Talos now supports Network Time Security (NTS) for secure time synchronization.
This feature enhances the security of NTP by providing cryptographic authentication of time sources.

NTS is enabled by default (without any configuration sources) for the default `time.cloudflare.com` time server
NTS can be enabled for custom time servers via the new `useNTS` field in the `TimeServerConfig` document.
"""

    [notes.tls13]
        title = "TLS 1.3 Minimum Version"
        description = """\
Talos now runs etcd and kube-apiserver with a minimum TLS version of 1.3, improving security by leveraging the latest TLS features and cipher suites.
Custom settings for cipher suites have been removed, as they are ignored when TLS 1.3 is used, which simplifies configuration and ensures the use of modern, secure defaults.
"""

    [notes.defaultInstaller]
        title = "Default Installer Image"
        description = """\
The default installer image has been updated to use the Image Factory.
"""

    [notes.hostdnsconfig]
        title = "Host DNS Configuration"
        description = """\
HostDNS configuration was moved from the v1alpha1 config `.machine.features.hostDNS` field to the new `hostDNS` in the `ResolverConfig` document.
"""

    [notes.httpProbe]
        title = "HTTP Probe Support"
        description = """\
Talos now supports HTTP network probes, allowing for monitoring of HTTP endpoints.
HTTP responses with status 200-399 are considered successful, while connection and transport errors are treated as failures.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"
