// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network/network.proto

package network

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"

	common "github.com/talos-systems/talos/api/common"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddressFamily int32

const (
	AddressFamily_AF_UNSPEC AddressFamily = 0
	AddressFamily_AF_INET   AddressFamily = 2
	AddressFamily_IPV4      AddressFamily = 2
	AddressFamily_AF_INET6  AddressFamily = 10
	AddressFamily_IPV6      AddressFamily = 10
)

var AddressFamily_name = map[int32]string{
	0: "AF_UNSPEC",
	2: "AF_INET",
	// Duplicate value: 2: "IPV4",
	10: "AF_INET6",
	// Duplicate value: 10: "IPV6",
}

var AddressFamily_value = map[string]int32{
	"AF_UNSPEC": 0,
	"AF_INET":   2,
	"IPV4":      2,
	"AF_INET6":  10,
	"IPV6":      10,
}

func (x AddressFamily) String() string {
	return proto.EnumName(AddressFamily_name, int32(x))
}

func (AddressFamily) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_96ad937ae012c472, []int{0}
}

type RouteProtocol int32

const (
	RouteProtocol_RTPROT_UNSPEC   RouteProtocol = 0
	RouteProtocol_RTPROT_REDIRECT RouteProtocol = 1
	RouteProtocol_RTPROT_KERNEL   RouteProtocol = 2
	RouteProtocol_RTPROT_BOOT     RouteProtocol = 3
	RouteProtocol_RTPROT_STATIC   RouteProtocol = 4
	RouteProtocol_RTPROT_GATED    RouteProtocol = 8
	RouteProtocol_RTPROT_RA       RouteProtocol = 9
	RouteProtocol_RTPROT_MRT      RouteProtocol = 10
	RouteProtocol_RTPROT_ZEBRA    RouteProtocol = 11
	RouteProtocol_RTPROT_BIRD     RouteProtocol = 12
	RouteProtocol_RTPROT_DNROUTED RouteProtocol = 13
	RouteProtocol_RTPROT_XORP     RouteProtocol = 14
	RouteProtocol_RTPROT_NTK      RouteProtocol = 15
	RouteProtocol_RTPROT_DHCP     RouteProtocol = 16
	RouteProtocol_RTPROT_MROUTED  RouteProtocol = 17
	RouteProtocol_RTPROT_BABEL    RouteProtocol = 42
)

var RouteProtocol_name = map[int32]string{
	0:  "RTPROT_UNSPEC",
	1:  "RTPROT_REDIRECT",
	2:  "RTPROT_KERNEL",
	3:  "RTPROT_BOOT",
	4:  "RTPROT_STATIC",
	8:  "RTPROT_GATED",
	9:  "RTPROT_RA",
	10: "RTPROT_MRT",
	11: "RTPROT_ZEBRA",
	12: "RTPROT_BIRD",
	13: "RTPROT_DNROUTED",
	14: "RTPROT_XORP",
	15: "RTPROT_NTK",
	16: "RTPROT_DHCP",
	17: "RTPROT_MROUTED",
	42: "RTPROT_BABEL",
}

var RouteProtocol_value = map[string]int32{
	"RTPROT_UNSPEC":   0,
	"RTPROT_REDIRECT": 1,
	"RTPROT_KERNEL":   2,
	"RTPROT_BOOT":     3,
	"RTPROT_STATIC":   4,
	"RTPROT_GATED":    8,
	"RTPROT_RA":       9,
	"RTPROT_MRT":      10,
	"RTPROT_ZEBRA":    11,
	"RTPROT_BIRD":     12,
	"RTPROT_DNROUTED": 13,
	"RTPROT_XORP":     14,
	"RTPROT_NTK":      15,
	"RTPROT_DHCP":     16,
	"RTPROT_MROUTED":  17,
	"RTPROT_BABEL":    42,
}

func (x RouteProtocol) String() string {
	return proto.EnumName(RouteProtocol_name, int32(x))
}

func (RouteProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_96ad937ae012c472, []int{1}
}

type InterfaceFlags int32

const (
	InterfaceFlags_FLAG_UNKNOWN        InterfaceFlags = 0
	InterfaceFlags_FLAG_UP             InterfaceFlags = 1
	InterfaceFlags_FLAG_BROADCAST      InterfaceFlags = 2
	InterfaceFlags_FLAG_LOOPBACK       InterfaceFlags = 3
	InterfaceFlags_FLAG_POINT_TO_POINT InterfaceFlags = 4
	InterfaceFlags_FLAG_MULTICAST      InterfaceFlags = 5
)

var InterfaceFlags_name = map[int32]string{
	0: "FLAG_UNKNOWN",
	1: "FLAG_UP",
	2: "FLAG_BROADCAST",
	3: "FLAG_LOOPBACK",
	4: "FLAG_POINT_TO_POINT",
	5: "FLAG_MULTICAST",
}

var InterfaceFlags_value = map[string]int32{
	"FLAG_UNKNOWN":        0,
	"FLAG_UP":             1,
	"FLAG_BROADCAST":      2,
	"FLAG_LOOPBACK":       3,
	"FLAG_POINT_TO_POINT": 4,
	"FLAG_MULTICAST":      5,
}

func (x InterfaceFlags) String() string {
	return proto.EnumName(InterfaceFlags_name, int32(x))
}

func (InterfaceFlags) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_96ad937ae012c472, []int{2}
}

// The messages message containing the routes.
type RoutesResponse struct {
	Messages             []*Routes `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoutesResponse) Reset()         { *m = RoutesResponse{} }
func (m *RoutesResponse) String() string { return proto.CompactTextString(m) }
func (*RoutesResponse) ProtoMessage()    {}
func (*RoutesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ad937ae012c472, []int{0}
}

func (m *RoutesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutesResponse.Unmarshal(m, b)
}

func (m *RoutesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutesResponse.Marshal(b, m, deterministic)
}

func (m *RoutesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutesResponse.Merge(m, src)
}

func (m *RoutesResponse) XXX_Size() int {
	return xxx_messageInfo_RoutesResponse.Size(m)
}

func (m *RoutesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoutesResponse proto.InternalMessageInfo

func (m *RoutesResponse) GetMessages() []*Routes {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Routes struct {
	Metadata             *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Routes               []*Route         `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Routes) Reset()         { *m = Routes{} }
func (m *Routes) String() string { return proto.CompactTextString(m) }
func (*Routes) ProtoMessage()    {}
func (*Routes) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ad937ae012c472, []int{1}
}

func (m *Routes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Routes.Unmarshal(m, b)
}

func (m *Routes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Routes.Marshal(b, m, deterministic)
}

func (m *Routes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Routes.Merge(m, src)
}

func (m *Routes) XXX_Size() int {
	return xxx_messageInfo_Routes.Size(m)
}

func (m *Routes) XXX_DiscardUnknown() {
	xxx_messageInfo_Routes.DiscardUnknown(m)
}

var xxx_messageInfo_Routes proto.InternalMessageInfo

func (m *Routes) GetMetadata() *common.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Routes) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

// The messages message containing a route.
type Route struct {
	// Interface is the interface over which traffic to this destination should be sent
	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// Destination is the network prefix CIDR which this route provides
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	// Gateway is the gateway address to which traffic to this destination should be sent
	Gateway string `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Metric is the priority of the route, where lower metrics have higher priorities
	Metric uint32 `protobuf:"varint,4,opt,name=metric,proto3" json:"metric,omitempty"`
	// Scope desribes the scope of this route
	Scope uint32 `protobuf:"varint,5,opt,name=scope,proto3" json:"scope,omitempty"`
	// Source is the source prefix CIDR for the route, if one is defined
	Source string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	// Family is the address family of the route.  Currently, the only options are AF_INET (IPV4) and AF_INET6 (IPV6).
	Family AddressFamily `protobuf:"varint,7,opt,name=family,proto3,enum=network.AddressFamily" json:"family,omitempty"`
	// Protocol is the protocol by which this route came to be in place
	Protocol RouteProtocol `protobuf:"varint,8,opt,name=protocol,proto3,enum=network.RouteProtocol" json:"protocol,omitempty"`
	// Flags indicate any special flags on the route
	Flags                uint32   `protobuf:"varint,9,opt,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ad937ae012c472, []int{2}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}

func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}

func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}

func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}

func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *Route) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Route) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *Route) GetMetric() uint32 {
	if m != nil {
		return m.Metric
	}
	return 0
}

func (m *Route) GetScope() uint32 {
	if m != nil {
		return m.Scope
	}
	return 0
}

func (m *Route) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Route) GetFamily() AddressFamily {
	if m != nil {
		return m.Family
	}
	return AddressFamily_AF_UNSPEC
}

func (m *Route) GetProtocol() RouteProtocol {
	if m != nil {
		return m.Protocol
	}
	return RouteProtocol_RTPROT_UNSPEC
}

func (m *Route) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type InterfacesResponse struct {
	Messages             []*Interfaces `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InterfacesResponse) Reset()         { *m = InterfacesResponse{} }
func (m *InterfacesResponse) String() string { return proto.CompactTextString(m) }
func (*InterfacesResponse) ProtoMessage()    {}
func (*InterfacesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ad937ae012c472, []int{3}
}

func (m *InterfacesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfacesResponse.Unmarshal(m, b)
}

func (m *InterfacesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfacesResponse.Marshal(b, m, deterministic)
}

func (m *InterfacesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfacesResponse.Merge(m, src)
}

func (m *InterfacesResponse) XXX_Size() int {
	return xxx_messageInfo_InterfacesResponse.Size(m)
}

func (m *InterfacesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfacesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InterfacesResponse proto.InternalMessageInfo

func (m *InterfacesResponse) GetMessages() []*Interfaces {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Interfaces struct {
	Metadata             *common.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Interfaces           []*Interface     `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Interfaces) Reset()         { *m = Interfaces{} }
func (m *Interfaces) String() string { return proto.CompactTextString(m) }
func (*Interfaces) ProtoMessage()    {}
func (*Interfaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ad937ae012c472, []int{4}
}

func (m *Interfaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interfaces.Unmarshal(m, b)
}

func (m *Interfaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interfaces.Marshal(b, m, deterministic)
}

func (m *Interfaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interfaces.Merge(m, src)
}

func (m *Interfaces) XXX_Size() int {
	return xxx_messageInfo_Interfaces.Size(m)
}

func (m *Interfaces) XXX_DiscardUnknown() {
	xxx_messageInfo_Interfaces.DiscardUnknown(m)
}

var xxx_messageInfo_Interfaces proto.InternalMessageInfo

func (m *Interfaces) GetMetadata() *common.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Interfaces) GetInterfaces() []*Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

// Interface represents a net.Interface
type Interface struct {
	Index                uint32         `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Mtu                  uint32         `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Hardwareaddr         string         `protobuf:"bytes,4,opt,name=hardwareaddr,proto3" json:"hardwareaddr,omitempty"`
	Flags                InterfaceFlags `protobuf:"varint,5,opt,name=flags,proto3,enum=network.InterfaceFlags" json:"flags,omitempty"`
	Ipaddress            []string       `protobuf:"bytes,6,rep,name=ipaddress,proto3" json:"ipaddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Interface) Reset()         { *m = Interface{} }
func (m *Interface) String() string { return proto.CompactTextString(m) }
func (*Interface) ProtoMessage()    {}
func (*Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ad937ae012c472, []int{5}
}

func (m *Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interface.Unmarshal(m, b)
}

func (m *Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interface.Marshal(b, m, deterministic)
}

func (m *Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interface.Merge(m, src)
}

func (m *Interface) XXX_Size() int {
	return xxx_messageInfo_Interface.Size(m)
}

func (m *Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Interface proto.InternalMessageInfo

func (m *Interface) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Interface) GetMtu() uint32 {
	if m != nil {
		return m.Mtu
	}
	return 0
}

func (m *Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Interface) GetHardwareaddr() string {
	if m != nil {
		return m.Hardwareaddr
	}
	return ""
}

func (m *Interface) GetFlags() InterfaceFlags {
	if m != nil {
		return m.Flags
	}
	return InterfaceFlags_FLAG_UNKNOWN
}

func (m *Interface) GetIpaddress() []string {
	if m != nil {
		return m.Ipaddress
	}
	return nil
}

func init() {
	proto.RegisterEnum("network.AddressFamily", AddressFamily_name, AddressFamily_value)
	proto.RegisterEnum("network.RouteProtocol", RouteProtocol_name, RouteProtocol_value)
	proto.RegisterEnum("network.InterfaceFlags", InterfaceFlags_name, InterfaceFlags_value)
	proto.RegisterType((*RoutesResponse)(nil), "network.RoutesResponse")
	proto.RegisterType((*Routes)(nil), "network.Routes")
	proto.RegisterType((*Route)(nil), "network.Route")
	proto.RegisterType((*InterfacesResponse)(nil), "network.InterfacesResponse")
	proto.RegisterType((*Interfaces)(nil), "network.Interfaces")
	proto.RegisterType((*Interface)(nil), "network.Interface")
}

func init() { proto.RegisterFile("network/network.proto", fileDescriptor_96ad937ae012c472) }

var fileDescriptor_96ad937ae012c472 = []byte{
	// 828 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x73, 0xeb, 0x34,
	0x14, 0xc5, 0xf9, 0x6a, 0x72, 0x53, 0x27, 0xaa, 0x0a, 0xad, 0xa7, 0x8f, 0x45, 0x26, 0x0b, 0xa6,
	0x13, 0x78, 0xc9, 0x4c, 0x60, 0xde, 0x0c, 0x0b, 0x16, 0x4e, 0xe2, 0x3c, 0x32, 0x49, 0x6d, 0xa3,
	0xba, 0xc0, 0xbc, 0x05, 0x1d, 0xd5, 0x56, 0xf3, 0x3c, 0xc4, 0x1f, 0x63, 0x39, 0x94, 0xae, 0xd9,
	0xf3, 0x1f, 0xf8, 0x05, 0x6c, 0xf9, 0x79, 0x8c, 0x65, 0xd9, 0x71, 0x5e, 0x61, 0xf1, 0x56, 0xd6,
	0x3d, 0xf7, 0xdc, 0x7b, 0x24, 0x1d, 0x49, 0x86, 0xcf, 0x42, 0x96, 0x3e, 0x45, 0xc9, 0xaf, 0x13,
	0xf9, 0x1d, 0xc7, 0x49, 0x94, 0x46, 0xf8, 0x44, 0x86, 0x57, 0xaf, 0xb6, 0x51, 0xb4, 0xdd, 0xb1,
	0x89, 0x80, 0x1f, 0xf6, 0x8f, 0x13, 0x16, 0xc4, 0xe9, 0x73, 0xce, 0xba, 0x3a, 0x77, 0xa3, 0x20,
	0x88, 0xc2, 0x49, 0xfe, 0xc9, 0xc1, 0xe1, 0x77, 0xd0, 0x23, 0xd1, 0x3e, 0x65, 0x9c, 0x30, 0x1e,
	0x47, 0x21, 0x67, 0xf8, 0x4b, 0x68, 0x07, 0x8c, 0x73, 0xba, 0x65, 0x5c, 0x53, 0x06, 0xf5, 0xeb,
	0xee, 0xb4, 0x3f, 0x2e, 0xe4, 0x24, 0xb5, 0x24, 0x0c, 0x7f, 0x81, 0x56, 0x8e, 0xe1, 0xaf, 0xb2,
	0xb2, 0x94, 0x7a, 0x34, 0xa5, 0x9a, 0x32, 0x50, 0xae, 0xbb, 0x53, 0x34, 0x96, 0x4a, 0x37, 0x12,
	0x27, 0x25, 0x03, 0x7f, 0x01, 0xad, 0x44, 0xd4, 0x69, 0x35, 0x21, 0xd1, 0x3b, 0x96, 0x20, 0x32,
	0x3b, 0xfc, 0xab, 0x06, 0x4d, 0x81, 0xe0, 0xcf, 0xa1, 0xe3, 0x87, 0x29, 0x4b, 0x1e, 0xa9, 0xcb,
	0x84, 0x40, 0x87, 0x1c, 0x00, 0x3c, 0x80, 0xae, 0xc7, 0x78, 0xea, 0x87, 0x34, 0xf5, 0xa3, 0x50,
	0xab, 0x89, 0x7c, 0x15, 0xc2, 0x1a, 0x9c, 0x6c, 0x69, 0xca, 0x9e, 0xe8, 0xb3, 0x56, 0x17, 0xd9,
	0x22, 0xc4, 0x17, 0xd0, 0x0a, 0x58, 0x9a, 0xf8, 0xae, 0xd6, 0x18, 0x28, 0xd7, 0x2a, 0x91, 0x11,
	0xfe, 0x14, 0x9a, 0xdc, 0x8d, 0x62, 0xa6, 0x35, 0x05, 0x9c, 0x07, 0x19, 0x9b, 0x47, 0xfb, 0xc4,
	0x65, 0x5a, 0x4b, 0xb4, 0x91, 0x11, 0x1e, 0x43, 0xeb, 0x91, 0x06, 0xfe, 0xee, 0x59, 0x3b, 0x19,
	0x28, 0xd7, 0xbd, 0xe9, 0x45, 0xb9, 0x22, 0xdd, 0xf3, 0x12, 0xc6, 0xf9, 0x52, 0x64, 0x89, 0x64,
	0xe1, 0x29, 0xb4, 0x85, 0x03, 0x6e, 0xb4, 0xd3, 0xda, 0x1f, 0x54, 0x88, 0x15, 0xdb, 0x32, 0x4b,
	0x4a, 0x5e, 0x36, 0xa3, 0xc7, 0x1d, 0xdd, 0x72, 0xad, 0x93, 0xcf, 0x48, 0x04, 0x43, 0x03, 0xf0,
	0xaa, 0xd8, 0x88, 0x83, 0x8d, 0x93, 0x17, 0x36, 0x9e, 0x97, 0xfd, 0x2b, 0xf4, 0x83, 0x95, 0x21,
	0xc0, 0x01, 0xff, 0x48, 0x3b, 0xa7, 0x00, 0xa5, 0x17, 0x85, 0xa5, 0xf8, 0xa5, 0x1c, 0xa9, 0xb0,
	0x86, 0xff, 0x28, 0xd0, 0x29, 0x33, 0xd9, 0xd2, 0xfc, 0xd0, 0x63, 0xbf, 0x0b, 0x31, 0x95, 0xe4,
	0x01, 0x46, 0x50, 0x0f, 0xd2, 0xbd, 0xb0, 0x53, 0x25, 0xd9, 0x10, 0x63, 0x68, 0x84, 0x34, 0x60,
	0xd2, 0x43, 0x31, 0xc6, 0x43, 0x38, 0x7d, 0x4f, 0x13, 0xef, 0x89, 0x26, 0x8c, 0x7a, 0x5e, 0x22,
	0x6c, 0xec, 0x90, 0x23, 0x0c, 0xbf, 0x2e, 0xb6, 0xae, 0x29, 0xf6, 0xfa, 0xf2, 0xe5, 0xe4, 0x96,
	0x59, 0x5a, 0xee, 0xa9, 0x38, 0x6d, 0x31, 0xcd, 0x8d, 0xd3, 0x5a, 0x83, 0xba, 0x38, 0x6d, 0x05,
	0x30, 0xfa, 0x01, 0xd4, 0x23, 0x53, 0xb1, 0x0a, 0x1d, 0x7d, 0x79, 0x7f, 0x67, 0xde, 0xda, 0xc6,
	0x1c, 0x7d, 0x82, 0xbb, 0x70, 0xa2, 0x2f, 0xef, 0x57, 0xa6, 0xe1, 0xa0, 0x1a, 0x6e, 0x43, 0x63,
	0x65, 0xff, 0xf8, 0x0d, 0xaa, 0xe1, 0x53, 0x68, 0x4b, 0xf8, 0x0d, 0x02, 0x89, 0xbf, 0x41, 0x70,
	0x55, 0x43, 0xca, 0xe8, 0xef, 0x1a, 0xa8, 0x47, 0xb6, 0xe3, 0x33, 0x50, 0x89, 0x63, 0x13, 0xcb,
	0x39, 0xf4, 0x3d, 0x87, 0xbe, 0x84, 0x88, 0xb1, 0x58, 0x11, 0x63, 0xee, 0x20, 0xa5, 0xc2, 0x5b,
	0x1b, 0xc4, 0x34, 0x36, 0xa8, 0x86, 0xfb, 0xd0, 0x95, 0xd0, 0xcc, 0xb2, 0x1c, 0x54, 0xaf, 0x70,
	0x6e, 0x1d, 0xdd, 0x59, 0xcd, 0x51, 0x03, 0x23, 0x38, 0x95, 0xd0, 0x5b, 0xdd, 0x31, 0x16, 0xa8,
	0x9d, 0x2d, 0xa2, 0xe8, 0xae, 0xa3, 0x0e, 0xee, 0x01, 0xc8, 0xf0, 0x86, 0x38, 0x08, 0x2a, 0x05,
	0xef, 0x8c, 0x19, 0xd1, 0x51, 0xb7, 0x2a, 0xb3, 0x22, 0x0b, 0x74, 0x5a, 0x99, 0xdf, 0xc2, 0x24,
	0xd6, 0x5d, 0xd6, 0x56, 0xad, 0xb0, 0x7e, 0xb6, 0x88, 0x8d, 0x7a, 0x95, 0xc6, 0xa6, 0xb3, 0x46,
	0xfd, 0x0a, 0x61, 0xf1, 0xfd, 0xdc, 0x46, 0x08, 0x63, 0xe8, 0x95, 0xca, 0x79, 0x97, 0xb3, 0x8a,
	0xfa, 0x4c, 0x9f, 0x19, 0x1b, 0x34, 0x1a, 0xfd, 0xa1, 0x40, 0xef, 0xd8, 0xbc, 0x8c, 0xb4, 0xdc,
	0xe8, 0x6f, 0xef, 0xef, 0xcc, 0xb5, 0x69, 0xfd, 0x64, 0xe6, 0x4e, 0xe4, 0x88, 0x8d, 0x94, 0xac,
	0xaf, 0x08, 0x66, 0xc4, 0xd2, 0x17, 0x73, 0xfd, 0x36, 0x73, 0xe7, 0x0c, 0x54, 0x81, 0x6d, 0x2c,
	0xcb, 0x9e, 0xe9, 0xf3, 0x35, 0xaa, 0xe3, 0x4b, 0x38, 0x17, 0x90, 0x6d, 0xad, 0x4c, 0xe7, 0xde,
	0xb1, 0xf2, 0x01, 0x6a, 0x94, 0xf5, 0x37, 0x77, 0x1b, 0x67, 0x25, 0xea, 0x9b, 0xd3, 0x3f, 0x15,
	0xe8, 0x99, 0xf9, 0x51, 0xba, 0x65, 0xc9, 0x6f, 0xbe, 0xcb, 0xf0, 0xb7, 0xe5, 0x9b, 0x78, 0x31,
	0xce, 0xdf, 0xe3, 0x71, 0xf1, 0x1e, 0x8f, 0x8d, 0xec, 0x3d, 0xbe, 0xba, 0xfc, 0xf0, 0x41, 0x2d,
	0x2e, 0xad, 0x7e, 0x74, 0x07, 0xff, 0xaf, 0xfc, 0xd5, 0x7f, 0x5d, 0x64, 0xd9, 0x62, 0xb6, 0x86,
	0xbe, 0x1b, 0x05, 0x25, 0x83, 0xc6, 0xfe, 0x0c, 0xe4, 0x04, 0xf5, 0xd8, 0xb7, 0x95, 0x77, 0xa3,
	0xad, 0x9f, 0xbe, 0xdf, 0x3f, 0x64, 0xb7, 0x79, 0x92, 0xd2, 0x5d, 0xc4, 0x5f, 0xf3, 0x67, 0x9e,
	0xb2, 0x80, 0xe7, 0xd1, 0x84, 0xc6, 0x7e, 0xf1, 0x7b, 0x79, 0x68, 0x09, 0xe5, 0xaf, 0xff, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x06, 0x63, 0x99, 0xc9, 0x78, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConn
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NetworkServiceClient is the client API for NetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkServiceClient interface {
	Routes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RoutesResponse, error)
	Interfaces(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InterfacesResponse, error)
}

type networkServiceClient struct {
	cc *grpc.ClientConn
}

func NewNetworkServiceClient(cc *grpc.ClientConn) NetworkServiceClient {
	return &networkServiceClient{cc}
}

func (c *networkServiceClient) Routes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RoutesResponse, error) {
	out := new(RoutesResponse)
	err := c.cc.Invoke(ctx, "/network.NetworkService/Routes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) Interfaces(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*InterfacesResponse, error) {
	out := new(InterfacesResponse)
	err := c.cc.Invoke(ctx, "/network.NetworkService/Interfaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServiceServer is the server API for NetworkService service.
type NetworkServiceServer interface {
	Routes(context.Context, *empty.Empty) (*RoutesResponse, error)
	Interfaces(context.Context, *empty.Empty) (*InterfacesResponse, error)
}

func RegisterNetworkServiceServer(s *grpc.Server, srv NetworkServiceServer) {
	s.RegisterService(&_NetworkService_serviceDesc, srv)
}

func _NetworkService_Routes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Routes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.NetworkService/Routes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Routes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_Interfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Interfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.NetworkService/Interfaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Interfaces(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "network.NetworkService",
	HandlerType: (*NetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Routes",
			Handler:    _NetworkService_Routes_Handler,
		},
		{
			MethodName: "Interfaces",
			Handler:    _NetworkService_Interfaces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/network.proto",
}
