// Code generated by protoc-gen-go. DO NOT EDIT.
// source: machine/machine.proto

package machine

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"

	common "github.com/talos-systems/talos/api/common"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// rpc reboot
// The response message containing the reboot status.
type RebootResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RebootResponse) Reset()         { *m = RebootResponse{} }
func (m *RebootResponse) String() string { return proto.CompactTextString(m) }
func (*RebootResponse) ProtoMessage()    {}
func (*RebootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{0}
}

func (m *RebootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebootResponse.Unmarshal(m, b)
}

func (m *RebootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebootResponse.Marshal(b, m, deterministic)
}

func (m *RebootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebootResponse.Merge(m, src)
}

func (m *RebootResponse) XXX_Size() int {
	return xxx_messageInfo_RebootResponse.Size(m)
}

func (m *RebootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RebootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RebootResponse proto.InternalMessageInfo

func (m *RebootResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type RebootReply struct {
	Response             []*RebootResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RebootReply) Reset()         { *m = RebootReply{} }
func (m *RebootReply) String() string { return proto.CompactTextString(m) }
func (*RebootReply) ProtoMessage()    {}
func (*RebootReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{1}
}

func (m *RebootReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebootReply.Unmarshal(m, b)
}

func (m *RebootReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebootReply.Marshal(b, m, deterministic)
}

func (m *RebootReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebootReply.Merge(m, src)
}

func (m *RebootReply) XXX_Size() int {
	return xxx_messageInfo_RebootReply.Size(m)
}

func (m *RebootReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RebootReply.DiscardUnknown(m)
}

var xxx_messageInfo_RebootReply proto.InternalMessageInfo

func (m *RebootReply) GetResponse() []*RebootResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

// rpc reset
// The response message containing the restart status.
type ResetResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ResetResponse) Reset()         { *m = ResetResponse{} }
func (m *ResetResponse) String() string { return proto.CompactTextString(m) }
func (*ResetResponse) ProtoMessage()    {}
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{2}
}

func (m *ResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetResponse.Unmarshal(m, b)
}

func (m *ResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetResponse.Marshal(b, m, deterministic)
}

func (m *ResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetResponse.Merge(m, src)
}

func (m *ResetResponse) XXX_Size() int {
	return xxx_messageInfo_ResetResponse.Size(m)
}

func (m *ResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetResponse proto.InternalMessageInfo

func (m *ResetResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ResetReply struct {
	Response             []*ResetResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResetReply) Reset()         { *m = ResetReply{} }
func (m *ResetReply) String() string { return proto.CompactTextString(m) }
func (*ResetReply) ProtoMessage()    {}
func (*ResetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{3}
}

func (m *ResetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetReply.Unmarshal(m, b)
}

func (m *ResetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetReply.Marshal(b, m, deterministic)
}

func (m *ResetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetReply.Merge(m, src)
}

func (m *ResetReply) XXX_Size() int {
	return xxx_messageInfo_ResetReply.Size(m)
}

func (m *ResetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetReply.DiscardUnknown(m)
}

var xxx_messageInfo_ResetReply proto.InternalMessageInfo

func (m *ResetReply) GetResponse() []*ResetResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

// rpc shutdown
// The response message containing the shutdown status.
type ShutdownResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{4}
}

func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}

func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}

func (m *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(m, src)
}

func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}

func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

func (m *ShutdownResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ShutdownReply struct {
	Response             []*ShutdownResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ShutdownReply) Reset()         { *m = ShutdownReply{} }
func (m *ShutdownReply) String() string { return proto.CompactTextString(m) }
func (*ShutdownReply) ProtoMessage()    {}
func (*ShutdownReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{5}
}

func (m *ShutdownReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownReply.Unmarshal(m, b)
}

func (m *ShutdownReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownReply.Marshal(b, m, deterministic)
}

func (m *ShutdownReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownReply.Merge(m, src)
}

func (m *ShutdownReply) XXX_Size() int {
	return xxx_messageInfo_ShutdownReply.Size(m)
}

func (m *ShutdownReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownReply proto.InternalMessageInfo

func (m *ShutdownReply) GetResponse() []*ShutdownResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

// rpc upgrade
type UpgradeRequest struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeRequest) Reset()         { *m = UpgradeRequest{} }
func (m *UpgradeRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradeRequest) ProtoMessage()    {}
func (*UpgradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{6}
}

func (m *UpgradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeRequest.Unmarshal(m, b)
}

func (m *UpgradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeRequest.Marshal(b, m, deterministic)
}

func (m *UpgradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeRequest.Merge(m, src)
}

func (m *UpgradeRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradeRequest.Size(m)
}

func (m *UpgradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeRequest proto.InternalMessageInfo

func (m *UpgradeRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type UpgradeResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Ack                  string                   `protobuf:"bytes,2,opt,name=ack,proto3" json:"ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UpgradeResponse) Reset()         { *m = UpgradeResponse{} }
func (m *UpgradeResponse) String() string { return proto.CompactTextString(m) }
func (*UpgradeResponse) ProtoMessage()    {}
func (*UpgradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{7}
}

func (m *UpgradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeResponse.Unmarshal(m, b)
}

func (m *UpgradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeResponse.Marshal(b, m, deterministic)
}

func (m *UpgradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeResponse.Merge(m, src)
}

func (m *UpgradeResponse) XXX_Size() int {
	return xxx_messageInfo_UpgradeResponse.Size(m)
}

func (m *UpgradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeResponse proto.InternalMessageInfo

func (m *UpgradeResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *UpgradeResponse) GetAck() string {
	if m != nil {
		return m.Ack
	}
	return ""
}

type UpgradeReply struct {
	Response             []*UpgradeResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpgradeReply) Reset()         { *m = UpgradeReply{} }
func (m *UpgradeReply) String() string { return proto.CompactTextString(m) }
func (*UpgradeReply) ProtoMessage()    {}
func (*UpgradeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{8}
}

func (m *UpgradeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeReply.Unmarshal(m, b)
}

func (m *UpgradeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeReply.Marshal(b, m, deterministic)
}

func (m *UpgradeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeReply.Merge(m, src)
}

func (m *UpgradeReply) XXX_Size() int {
	return xxx_messageInfo_UpgradeReply.Size(m)
}

func (m *UpgradeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeReply proto.InternalMessageInfo

func (m *UpgradeReply) GetResponse() []*UpgradeResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

// rpc servicelist
type ServiceListResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Services             []*ServiceInfo           `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ServiceListResponse) Reset()         { *m = ServiceListResponse{} }
func (m *ServiceListResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceListResponse) ProtoMessage()    {}
func (*ServiceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{9}
}

func (m *ServiceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceListResponse.Unmarshal(m, b)
}

func (m *ServiceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceListResponse.Marshal(b, m, deterministic)
}

func (m *ServiceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceListResponse.Merge(m, src)
}

func (m *ServiceListResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceListResponse.Size(m)
}

func (m *ServiceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceListResponse proto.InternalMessageInfo

func (m *ServiceListResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ServiceListResponse) GetServices() []*ServiceInfo {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServiceListReply struct {
	Response             []*ServiceListResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ServiceListReply) Reset()         { *m = ServiceListReply{} }
func (m *ServiceListReply) String() string { return proto.CompactTextString(m) }
func (*ServiceListReply) ProtoMessage()    {}
func (*ServiceListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{10}
}

func (m *ServiceListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceListReply.Unmarshal(m, b)
}

func (m *ServiceListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceListReply.Marshal(b, m, deterministic)
}

func (m *ServiceListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceListReply.Merge(m, src)
}

func (m *ServiceListReply) XXX_Size() int {
	return xxx_messageInfo_ServiceListReply.Size(m)
}

func (m *ServiceListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceListReply proto.InternalMessageInfo

func (m *ServiceListReply) GetResponse() []*ServiceListResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type ServiceInfo struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State                string         `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Events               *ServiceEvents `protobuf:"bytes,3,opt,name=events,proto3" json:"events,omitempty"`
	Health               *ServiceHealth `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{11}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}

func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}

func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}

func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}

func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ServiceInfo) GetEvents() *ServiceEvents {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *ServiceInfo) GetHealth() *ServiceHealth {
	if m != nil {
		return m.Health
	}
	return nil
}

type ServiceEvents struct {
	Events               []*ServiceEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ServiceEvents) Reset()         { *m = ServiceEvents{} }
func (m *ServiceEvents) String() string { return proto.CompactTextString(m) }
func (*ServiceEvents) ProtoMessage()    {}
func (*ServiceEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{12}
}

func (m *ServiceEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceEvents.Unmarshal(m, b)
}

func (m *ServiceEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceEvents.Marshal(b, m, deterministic)
}

func (m *ServiceEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceEvents.Merge(m, src)
}

func (m *ServiceEvents) XXX_Size() int {
	return xxx_messageInfo_ServiceEvents.Size(m)
}

func (m *ServiceEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceEvents.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceEvents proto.InternalMessageInfo

func (m *ServiceEvents) GetEvents() []*ServiceEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type ServiceEvent struct {
	Msg                  string               `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	State                string               `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ServiceEvent) Reset()         { *m = ServiceEvent{} }
func (m *ServiceEvent) String() string { return proto.CompactTextString(m) }
func (*ServiceEvent) ProtoMessage()    {}
func (*ServiceEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{13}
}

func (m *ServiceEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceEvent.Unmarshal(m, b)
}

func (m *ServiceEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceEvent.Marshal(b, m, deterministic)
}

func (m *ServiceEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceEvent.Merge(m, src)
}

func (m *ServiceEvent) XXX_Size() int {
	return xxx_messageInfo_ServiceEvent.Size(m)
}

func (m *ServiceEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceEvent proto.InternalMessageInfo

func (m *ServiceEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ServiceEvent) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ServiceEvent) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type ServiceHealth struct {
	Unknown              bool                 `protobuf:"varint,1,opt,name=unknown,proto3" json:"unknown,omitempty"`
	Healthy              bool                 `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LastMessage          string               `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	LastChange           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_change,json=lastChange,proto3" json:"last_change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ServiceHealth) Reset()         { *m = ServiceHealth{} }
func (m *ServiceHealth) String() string { return proto.CompactTextString(m) }
func (*ServiceHealth) ProtoMessage()    {}
func (*ServiceHealth) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{14}
}

func (m *ServiceHealth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceHealth.Unmarshal(m, b)
}

func (m *ServiceHealth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceHealth.Marshal(b, m, deterministic)
}

func (m *ServiceHealth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceHealth.Merge(m, src)
}

func (m *ServiceHealth) XXX_Size() int {
	return xxx_messageInfo_ServiceHealth.Size(m)
}

func (m *ServiceHealth) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceHealth.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceHealth proto.InternalMessageInfo

func (m *ServiceHealth) GetUnknown() bool {
	if m != nil {
		return m.Unknown
	}
	return false
}

func (m *ServiceHealth) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func (m *ServiceHealth) GetLastMessage() string {
	if m != nil {
		return m.LastMessage
	}
	return ""
}

func (m *ServiceHealth) GetLastChange() *timestamp.Timestamp {
	if m != nil {
		return m.LastChange
	}
	return nil
}

// rpc servicestart
type ServiceStartRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceStartRequest) Reset()         { *m = ServiceStartRequest{} }
func (m *ServiceStartRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceStartRequest) ProtoMessage()    {}
func (*ServiceStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{15}
}

func (m *ServiceStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStartRequest.Unmarshal(m, b)
}

func (m *ServiceStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStartRequest.Marshal(b, m, deterministic)
}

func (m *ServiceStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStartRequest.Merge(m, src)
}

func (m *ServiceStartRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceStartRequest.Size(m)
}

func (m *ServiceStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStartRequest proto.InternalMessageInfo

func (m *ServiceStartRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ServiceStartResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Resp                 string                   `protobuf:"bytes,2,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ServiceStartResponse) Reset()         { *m = ServiceStartResponse{} }
func (m *ServiceStartResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceStartResponse) ProtoMessage()    {}
func (*ServiceStartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{16}
}

func (m *ServiceStartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStartResponse.Unmarshal(m, b)
}

func (m *ServiceStartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStartResponse.Marshal(b, m, deterministic)
}

func (m *ServiceStartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStartResponse.Merge(m, src)
}

func (m *ServiceStartResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceStartResponse.Size(m)
}

func (m *ServiceStartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStartResponse proto.InternalMessageInfo

func (m *ServiceStartResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ServiceStartResponse) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

type ServiceStartReply struct {
	Response             []*ServiceStartResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ServiceStartReply) Reset()         { *m = ServiceStartReply{} }
func (m *ServiceStartReply) String() string { return proto.CompactTextString(m) }
func (*ServiceStartReply) ProtoMessage()    {}
func (*ServiceStartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{17}
}

func (m *ServiceStartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStartReply.Unmarshal(m, b)
}

func (m *ServiceStartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStartReply.Marshal(b, m, deterministic)
}

func (m *ServiceStartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStartReply.Merge(m, src)
}

func (m *ServiceStartReply) XXX_Size() int {
	return xxx_messageInfo_ServiceStartReply.Size(m)
}

func (m *ServiceStartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStartReply.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStartReply proto.InternalMessageInfo

func (m *ServiceStartReply) GetResponse() []*ServiceStartResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type ServiceStopRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceStopRequest) Reset()         { *m = ServiceStopRequest{} }
func (m *ServiceStopRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceStopRequest) ProtoMessage()    {}
func (*ServiceStopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{18}
}

func (m *ServiceStopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStopRequest.Unmarshal(m, b)
}

func (m *ServiceStopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStopRequest.Marshal(b, m, deterministic)
}

func (m *ServiceStopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStopRequest.Merge(m, src)
}

func (m *ServiceStopRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceStopRequest.Size(m)
}

func (m *ServiceStopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStopRequest proto.InternalMessageInfo

func (m *ServiceStopRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ServiceStopResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Resp                 string                   `protobuf:"bytes,2,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ServiceStopResponse) Reset()         { *m = ServiceStopResponse{} }
func (m *ServiceStopResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceStopResponse) ProtoMessage()    {}
func (*ServiceStopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{19}
}

func (m *ServiceStopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStopResponse.Unmarshal(m, b)
}

func (m *ServiceStopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStopResponse.Marshal(b, m, deterministic)
}

func (m *ServiceStopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStopResponse.Merge(m, src)
}

func (m *ServiceStopResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceStopResponse.Size(m)
}

func (m *ServiceStopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStopResponse proto.InternalMessageInfo

func (m *ServiceStopResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ServiceStopResponse) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

type ServiceStopReply struct {
	Response             []*ServiceStopResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ServiceStopReply) Reset()         { *m = ServiceStopReply{} }
func (m *ServiceStopReply) String() string { return proto.CompactTextString(m) }
func (*ServiceStopReply) ProtoMessage()    {}
func (*ServiceStopReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{20}
}

func (m *ServiceStopReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStopReply.Unmarshal(m, b)
}

func (m *ServiceStopReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStopReply.Marshal(b, m, deterministic)
}

func (m *ServiceStopReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStopReply.Merge(m, src)
}

func (m *ServiceStopReply) XXX_Size() int {
	return xxx_messageInfo_ServiceStopReply.Size(m)
}

func (m *ServiceStopReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStopReply.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStopReply proto.InternalMessageInfo

func (m *ServiceStopReply) GetResponse() []*ServiceStopResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type ServiceRestartRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRestartRequest) Reset()         { *m = ServiceRestartRequest{} }
func (m *ServiceRestartRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceRestartRequest) ProtoMessage()    {}
func (*ServiceRestartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{21}
}

func (m *ServiceRestartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRestartRequest.Unmarshal(m, b)
}

func (m *ServiceRestartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRestartRequest.Marshal(b, m, deterministic)
}

func (m *ServiceRestartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRestartRequest.Merge(m, src)
}

func (m *ServiceRestartRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceRestartRequest.Size(m)
}

func (m *ServiceRestartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRestartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRestartRequest proto.InternalMessageInfo

func (m *ServiceRestartRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ServiceRestartResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Resp                 string                   `protobuf:"bytes,2,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ServiceRestartResponse) Reset()         { *m = ServiceRestartResponse{} }
func (m *ServiceRestartResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceRestartResponse) ProtoMessage()    {}
func (*ServiceRestartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{22}
}

func (m *ServiceRestartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRestartResponse.Unmarshal(m, b)
}

func (m *ServiceRestartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRestartResponse.Marshal(b, m, deterministic)
}

func (m *ServiceRestartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRestartResponse.Merge(m, src)
}

func (m *ServiceRestartResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceRestartResponse.Size(m)
}

func (m *ServiceRestartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRestartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRestartResponse proto.InternalMessageInfo

func (m *ServiceRestartResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ServiceRestartResponse) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

type ServiceRestartReply struct {
	Response             []*ServiceRestartResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ServiceRestartReply) Reset()         { *m = ServiceRestartReply{} }
func (m *ServiceRestartReply) String() string { return proto.CompactTextString(m) }
func (*ServiceRestartReply) ProtoMessage()    {}
func (*ServiceRestartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{23}
}

func (m *ServiceRestartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRestartReply.Unmarshal(m, b)
}

func (m *ServiceRestartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRestartReply.Marshal(b, m, deterministic)
}

func (m *ServiceRestartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRestartReply.Merge(m, src)
}

func (m *ServiceRestartReply) XXX_Size() int {
	return xxx_messageInfo_ServiceRestartReply.Size(m)
}

func (m *ServiceRestartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRestartReply.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRestartReply proto.InternalMessageInfo

func (m *ServiceRestartReply) GetResponse() []*ServiceRestartResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

// Deprecated: Do not use.
type StartRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{24}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}

func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}

func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}

func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}

func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Deprecated: Do not use.
type StartReply struct {
	Resp                 string   `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartReply) Reset()         { *m = StartReply{} }
func (m *StartReply) String() string { return proto.CompactTextString(m) }
func (*StartReply) ProtoMessage()    {}
func (*StartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{25}
}

func (m *StartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReply.Unmarshal(m, b)
}

func (m *StartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReply.Marshal(b, m, deterministic)
}

func (m *StartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReply.Merge(m, src)
}

func (m *StartReply) XXX_Size() int {
	return xxx_messageInfo_StartReply.Size(m)
}

func (m *StartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReply.DiscardUnknown(m)
}

var xxx_messageInfo_StartReply proto.InternalMessageInfo

func (m *StartReply) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

// Deprecated: Do not use.
type StopRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{26}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}

func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}

func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}

func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}

func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Deprecated: Do not use.
type StopReply struct {
	Resp                 string   `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopReply) Reset()         { *m = StopReply{} }
func (m *StopReply) String() string { return proto.CompactTextString(m) }
func (*StopReply) ProtoMessage()    {}
func (*StopReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{27}
}

func (m *StopReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopReply.Unmarshal(m, b)
}

func (m *StopReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopReply.Marshal(b, m, deterministic)
}

func (m *StopReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopReply.Merge(m, src)
}

func (m *StopReply) XXX_Size() int {
	return xxx_messageInfo_StopReply.Size(m)
}

func (m *StopReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopReply proto.InternalMessageInfo

func (m *StopReply) GetResp() string {
	if m != nil {
		return m.Resp
	}
	return ""
}

// CopyOutRequest describes a request to copy data out of Talos node
//
// CopyOut produces .tar.gz archive which is streamed back to the caller
type CopyOutRequest struct {
	// Root path to start copying data out, it might be either a file or directory
	RootPath             string   `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyOutRequest) Reset()         { *m = CopyOutRequest{} }
func (m *CopyOutRequest) String() string { return proto.CompactTextString(m) }
func (*CopyOutRequest) ProtoMessage()    {}
func (*CopyOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{28}
}

func (m *CopyOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyOutRequest.Unmarshal(m, b)
}

func (m *CopyOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyOutRequest.Marshal(b, m, deterministic)
}

func (m *CopyOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyOutRequest.Merge(m, src)
}

func (m *CopyOutRequest) XXX_Size() int {
	return xxx_messageInfo_CopyOutRequest.Size(m)
}

func (m *CopyOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyOutRequest proto.InternalMessageInfo

func (m *CopyOutRequest) GetRootPath() string {
	if m != nil {
		return m.RootPath
	}
	return ""
}

// LSRequest describes a request to list the contents of a directory
type LSRequest struct {
	// Root indicates the root directory for the list.  If not indicated, '/' is
	// presumed.
	Root string `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// Recurse indicates that subdirectories should be recursed.
	Recurse bool `protobuf:"varint,2,opt,name=recurse,proto3" json:"recurse,omitempty"`
	// RecursionDepth indicates how many levels of subdirectories should be
	// recursed.  The default (0) indicates that no limit should be enforced.
	RecursionDepth       int32    `protobuf:"varint,3,opt,name=recursion_depth,json=recursionDepth,proto3" json:"recursion_depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LSRequest) Reset()         { *m = LSRequest{} }
func (m *LSRequest) String() string { return proto.CompactTextString(m) }
func (*LSRequest) ProtoMessage()    {}
func (*LSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{29}
}

func (m *LSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LSRequest.Unmarshal(m, b)
}

func (m *LSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LSRequest.Marshal(b, m, deterministic)
}

func (m *LSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LSRequest.Merge(m, src)
}

func (m *LSRequest) XXX_Size() int {
	return xxx_messageInfo_LSRequest.Size(m)
}

func (m *LSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LSRequest proto.InternalMessageInfo

func (m *LSRequest) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *LSRequest) GetRecurse() bool {
	if m != nil {
		return m.Recurse
	}
	return false
}

func (m *LSRequest) GetRecursionDepth() int32 {
	if m != nil {
		return m.RecursionDepth
	}
	return 0
}

// FileInfo describes a file or directory's information
type FileInfo struct {
	Metadata *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Name is the name (including prefixed path) of the file or directory
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Size indicates the number of bytes contained within the file
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Mode is the bitmap of UNIX mode/permission flags of the file
	Mode uint32 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	// Modified indicates the UNIX timestamp at which the file was last modified
	Modified int64 `protobuf:"varint,5,opt,name=modified,proto3" json:"modified,omitempty"`
	// IsDir indicates that the file is a directory
	IsDir bool `protobuf:"varint,6,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	// Error describes any error encountered while trying to read the file
	// information.
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// Link is filled with symlink target
	Link string `protobuf:"bytes,8,opt,name=link,proto3" json:"link,omitempty"`
	// RelativeName is the name of the file or directory relative to the RootPath
	RelativeName         string   `protobuf:"bytes,9,opt,name=relative_name,json=relativeName,proto3" json:"relative_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{30}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}

func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}

func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}

func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}

func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileInfo) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *FileInfo) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *FileInfo) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FileInfo) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *FileInfo) GetRelativeName() string {
	if m != nil {
		return m.RelativeName
	}
	return ""
}

// The response message containing the requested df stats.
type MountsResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Stats                []*MountStat             `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MountsResponse) Reset()         { *m = MountsResponse{} }
func (m *MountsResponse) String() string { return proto.CompactTextString(m) }
func (*MountsResponse) ProtoMessage()    {}
func (*MountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{31}
}

func (m *MountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountsResponse.Unmarshal(m, b)
}

func (m *MountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountsResponse.Marshal(b, m, deterministic)
}

func (m *MountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountsResponse.Merge(m, src)
}

func (m *MountsResponse) XXX_Size() int {
	return xxx_messageInfo_MountsResponse.Size(m)
}

func (m *MountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MountsResponse proto.InternalMessageInfo

func (m *MountsResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MountsResponse) GetStats() []*MountStat {
	if m != nil {
		return m.Stats
	}
	return nil
}

type MountsReply struct {
	Response             []*MountsResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MountsReply) Reset()         { *m = MountsReply{} }
func (m *MountsReply) String() string { return proto.CompactTextString(m) }
func (*MountsReply) ProtoMessage()    {}
func (*MountsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{32}
}

func (m *MountsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountsReply.Unmarshal(m, b)
}

func (m *MountsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountsReply.Marshal(b, m, deterministic)
}

func (m *MountsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountsReply.Merge(m, src)
}

func (m *MountsReply) XXX_Size() int {
	return xxx_messageInfo_MountsReply.Size(m)
}

func (m *MountsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MountsReply.DiscardUnknown(m)
}

var xxx_messageInfo_MountsReply proto.InternalMessageInfo

func (m *MountsReply) GetResponse() []*MountsResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

// The response message containing the requested processes.
type MountStat struct {
	Filesystem           string   `protobuf:"bytes,1,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Available            uint64   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	MountedOn            string   `protobuf:"bytes,4,opt,name=mounted_on,json=mountedOn,proto3" json:"mounted_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountStat) Reset()         { *m = MountStat{} }
func (m *MountStat) String() string { return proto.CompactTextString(m) }
func (*MountStat) ProtoMessage()    {}
func (*MountStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{33}
}

func (m *MountStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountStat.Unmarshal(m, b)
}

func (m *MountStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountStat.Marshal(b, m, deterministic)
}

func (m *MountStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountStat.Merge(m, src)
}

func (m *MountStat) XXX_Size() int {
	return xxx_messageInfo_MountStat.Size(m)
}

func (m *MountStat) XXX_DiscardUnknown() {
	xxx_messageInfo_MountStat.DiscardUnknown(m)
}

var xxx_messageInfo_MountStat proto.InternalMessageInfo

func (m *MountStat) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

func (m *MountStat) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *MountStat) GetAvailable() uint64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *MountStat) GetMountedOn() string {
	if m != nil {
		return m.MountedOn
	}
	return ""
}

type VersionResponse struct {
	Metadata             *common.ResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Version              *VersionInfo             `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Platform             *PlatformInfo            `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{34}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}

func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}

func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}

func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}

func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetMetadata() *common.ResponseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *VersionResponse) GetVersion() *VersionInfo {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *VersionResponse) GetPlatform() *PlatformInfo {
	if m != nil {
		return m.Platform
	}
	return nil
}

type VersionReply struct {
	Response             []*VersionResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VersionReply) Reset()         { *m = VersionReply{} }
func (m *VersionReply) String() string { return proto.CompactTextString(m) }
func (*VersionReply) ProtoMessage()    {}
func (*VersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{35}
}

func (m *VersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionReply.Unmarshal(m, b)
}

func (m *VersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionReply.Marshal(b, m, deterministic)
}

func (m *VersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionReply.Merge(m, src)
}

func (m *VersionReply) XXX_Size() int {
	return xxx_messageInfo_VersionReply.Size(m)
}

func (m *VersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_VersionReply proto.InternalMessageInfo

func (m *VersionReply) GetResponse() []*VersionResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type VersionInfo struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Sha                  string   `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	Built                string   `protobuf:"bytes,3,opt,name=built,proto3" json:"built,omitempty"`
	GoVersion            string   `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	Os                   string   `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionInfo) Reset()         { *m = VersionInfo{} }
func (m *VersionInfo) String() string { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()    {}
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{36}
}

func (m *VersionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionInfo.Unmarshal(m, b)
}

func (m *VersionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionInfo.Marshal(b, m, deterministic)
}

func (m *VersionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionInfo.Merge(m, src)
}

func (m *VersionInfo) XXX_Size() int {
	return xxx_messageInfo_VersionInfo.Size(m)
}

func (m *VersionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VersionInfo proto.InternalMessageInfo

func (m *VersionInfo) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *VersionInfo) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

func (m *VersionInfo) GetBuilt() string {
	if m != nil {
		return m.Built
	}
	return ""
}

func (m *VersionInfo) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *VersionInfo) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *VersionInfo) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

type PlatformInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode                 string   `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatformInfo) Reset()         { *m = PlatformInfo{} }
func (m *PlatformInfo) String() string { return proto.CompactTextString(m) }
func (*PlatformInfo) ProtoMessage()    {}
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{37}
}

func (m *PlatformInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformInfo.Unmarshal(m, b)
}

func (m *PlatformInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformInfo.Marshal(b, m, deterministic)
}

func (m *PlatformInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformInfo.Merge(m, src)
}

func (m *PlatformInfo) XXX_Size() int {
	return xxx_messageInfo_PlatformInfo.Size(m)
}

func (m *PlatformInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformInfo proto.InternalMessageInfo

func (m *PlatformInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlatformInfo) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

// rpc logs
// The request message containing the process name.
type LogsRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// driver might be default "containerd" or "cri"
	Driver               common.ContainerDriver `protobuf:"varint,3,opt,name=driver,proto3,enum=common.ContainerDriver" json:"driver,omitempty"`
	Follow               bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LogsRequest) Reset()         { *m = LogsRequest{} }
func (m *LogsRequest) String() string { return proto.CompactTextString(m) }
func (*LogsRequest) ProtoMessage()    {}
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{38}
}

func (m *LogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogsRequest.Unmarshal(m, b)
}

func (m *LogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogsRequest.Marshal(b, m, deterministic)
}

func (m *LogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogsRequest.Merge(m, src)
}

func (m *LogsRequest) XXX_Size() int {
	return xxx_messageInfo_LogsRequest.Size(m)
}

func (m *LogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogsRequest proto.InternalMessageInfo

func (m *LogsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *LogsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LogsRequest) GetDriver() common.ContainerDriver {
	if m != nil {
		return m.Driver
	}
	return common.ContainerDriver_CONTAINERD
}

func (m *LogsRequest) GetFollow() bool {
	if m != nil {
		return m.Follow
	}
	return false
}

type ReadRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{39}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}

func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}

func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}

func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}

func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*RebootResponse)(nil), "machine.RebootResponse")
	proto.RegisterType((*RebootReply)(nil), "machine.RebootReply")
	proto.RegisterType((*ResetResponse)(nil), "machine.ResetResponse")
	proto.RegisterType((*ResetReply)(nil), "machine.ResetReply")
	proto.RegisterType((*ShutdownResponse)(nil), "machine.ShutdownResponse")
	proto.RegisterType((*ShutdownReply)(nil), "machine.ShutdownReply")
	proto.RegisterType((*UpgradeRequest)(nil), "machine.UpgradeRequest")
	proto.RegisterType((*UpgradeResponse)(nil), "machine.UpgradeResponse")
	proto.RegisterType((*UpgradeReply)(nil), "machine.UpgradeReply")
	proto.RegisterType((*ServiceListResponse)(nil), "machine.ServiceListResponse")
	proto.RegisterType((*ServiceListReply)(nil), "machine.ServiceListReply")
	proto.RegisterType((*ServiceInfo)(nil), "machine.ServiceInfo")
	proto.RegisterType((*ServiceEvents)(nil), "machine.ServiceEvents")
	proto.RegisterType((*ServiceEvent)(nil), "machine.ServiceEvent")
	proto.RegisterType((*ServiceHealth)(nil), "machine.ServiceHealth")
	proto.RegisterType((*ServiceStartRequest)(nil), "machine.ServiceStartRequest")
	proto.RegisterType((*ServiceStartResponse)(nil), "machine.ServiceStartResponse")
	proto.RegisterType((*ServiceStartReply)(nil), "machine.ServiceStartReply")
	proto.RegisterType((*ServiceStopRequest)(nil), "machine.ServiceStopRequest")
	proto.RegisterType((*ServiceStopResponse)(nil), "machine.ServiceStopResponse")
	proto.RegisterType((*ServiceStopReply)(nil), "machine.ServiceStopReply")
	proto.RegisterType((*ServiceRestartRequest)(nil), "machine.ServiceRestartRequest")
	proto.RegisterType((*ServiceRestartResponse)(nil), "machine.ServiceRestartResponse")
	proto.RegisterType((*ServiceRestartReply)(nil), "machine.ServiceRestartReply")
	proto.RegisterType((*StartRequest)(nil), "machine.StartRequest")
	proto.RegisterType((*StartReply)(nil), "machine.StartReply")
	proto.RegisterType((*StopRequest)(nil), "machine.StopRequest")
	proto.RegisterType((*StopReply)(nil), "machine.StopReply")
	proto.RegisterType((*CopyOutRequest)(nil), "machine.CopyOutRequest")
	proto.RegisterType((*LSRequest)(nil), "machine.LSRequest")
	proto.RegisterType((*FileInfo)(nil), "machine.FileInfo")
	proto.RegisterType((*MountsResponse)(nil), "machine.MountsResponse")
	proto.RegisterType((*MountsReply)(nil), "machine.MountsReply")
	proto.RegisterType((*MountStat)(nil), "machine.MountStat")
	proto.RegisterType((*VersionResponse)(nil), "machine.VersionResponse")
	proto.RegisterType((*VersionReply)(nil), "machine.VersionReply")
	proto.RegisterType((*VersionInfo)(nil), "machine.VersionInfo")
	proto.RegisterType((*PlatformInfo)(nil), "machine.PlatformInfo")
	proto.RegisterType((*LogsRequest)(nil), "machine.LogsRequest")
	proto.RegisterType((*ReadRequest)(nil), "machine.ReadRequest")
}

func init() { proto.RegisterFile("machine/machine.proto", fileDescriptor_84b4f59d98cc997c) }

var fileDescriptor_84b4f59d98cc997c = []byte{
	// 1498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6f, 0x13, 0x47,
	0x10, 0xd7, 0x39, 0x1f, 0xb6, 0xc7, 0x89, 0x03, 0x9b, 0x0f, 0x8c, 0x09, 0x5f, 0x07, 0x2d, 0x08,
	0x29, 0x0e, 0x0d, 0x01, 0x51, 0xa8, 0x2a, 0x0a, 0x09, 0xa2, 0x22, 0x01, 0x74, 0x69, 0x2b, 0xb5,
	0x2f, 0xee, 0xda, 0xde, 0xd8, 0x2b, 0xee, 0x6e, 0xaf, 0xb7, 0xeb, 0xa0, 0x54, 0xed, 0x5b, 0x1f,
	0xda, 0xbe, 0xf6, 0x4f, 0xe8, 0x5b, 0xff, 0xc8, 0xaa, 0xda, 0x4f, 0xaf, 0xcf, 0x71, 0x40, 0x0d,
	0x4f, 0xde, 0x9d, 0x9d, 0x9b, 0xf9, 0xfd, 0x76, 0x66, 0x67, 0x67, 0x0d, 0xab, 0x09, 0xee, 0x0e,
	0x68, 0x4a, 0x36, 0xcd, 0x6f, 0x2b, 0xcb, 0x99, 0x60, 0xa8, 0x6c, 0xa6, 0xcd, 0x4b, 0x7d, 0xc6,
	0xfa, 0x31, 0xd9, 0x54, 0xe2, 0xce, 0xf0, 0x70, 0x93, 0x24, 0x99, 0x38, 0xd6, 0x5a, 0xcd, 0xab,
	0xc5, 0x45, 0x41, 0x13, 0xc2, 0x05, 0x4e, 0x32, 0xa3, 0xb0, 0xdc, 0x65, 0x49, 0xc2, 0xd2, 0x4d,
	0xfd, 0xa3, 0x85, 0xe1, 0x73, 0xa8, 0x47, 0xa4, 0xc3, 0x98, 0x88, 0x08, 0xcf, 0x58, 0xca, 0x09,
	0xda, 0x86, 0x4a, 0x42, 0x04, 0xee, 0x61, 0x81, 0x1b, 0xc1, 0xb5, 0xe0, 0x76, 0x6d, 0xab, 0xd1,
	0x32, 0x9f, 0x58, 0x9d, 0x7d, 0xb3, 0x1e, 0x39, 0xcd, 0xf0, 0x29, 0xd4, 0xac, 0x9d, 0x2c, 0x3e,
	0x46, 0xf7, 0xa0, 0x92, 0x1b, 0xe5, 0x46, 0x70, 0x6d, 0xe6, 0x76, 0x6d, 0xeb, 0x42, 0xcb, 0x92,
	0x1a, 0xf7, 0x17, 0x39, 0xc5, 0x70, 0x17, 0x16, 0x23, 0xc2, 0xc9, 0x59, 0xa1, 0x3c, 0x01, 0x30,
	0x66, 0x24, 0x92, 0xad, 0x09, 0x24, 0x6b, 0x1e, 0x12, 0xcf, 0x9b, 0x07, 0xe4, 0x05, 0x9c, 0x3b,
	0x18, 0x0c, 0x45, 0x8f, 0xbd, 0x4b, 0xcf, 0x88, 0xe5, 0x39, 0x2c, 0x8e, 0x2c, 0x49, 0x38, 0xf7,
	0x27, 0xe0, 0x5c, 0x74, 0x70, 0x8a, 0x3e, 0x3d, 0x44, 0x9f, 0x42, 0xfd, 0xdb, 0xac, 0x9f, 0xe3,
	0x1e, 0x89, 0xc8, 0x4f, 0x43, 0xc2, 0x05, 0x5a, 0x81, 0x39, 0x9a, 0xe0, 0x3e, 0x51, 0x60, 0xaa,
	0x91, 0x9e, 0x84, 0xdf, 0xc3, 0x92, 0xd3, 0x3b, 0x0b, 0x70, 0x74, 0x0e, 0x66, 0x70, 0xf7, 0x6d,
	0xa3, 0xa4, 0x8c, 0xcb, 0x61, 0xb8, 0x03, 0x0b, 0xce, 0xb4, 0x64, 0xb2, 0x3d, 0xc1, 0xa4, 0xe1,
	0x98, 0x14, 0x30, 0x78, 0x44, 0x7e, 0x85, 0xe5, 0x03, 0x92, 0x1f, 0xd1, 0x2e, 0xd9, 0xa3, 0xfc,
	0x8c, 0x91, 0x46, 0x77, 0xa1, 0xc2, 0xb5, 0x31, 0xde, 0x28, 0x29, 0x08, 0x2b, 0xa3, 0xcd, 0xd4,
	0x0b, 0x5f, 0xa7, 0x87, 0x2c, 0x72, 0x5a, 0xe1, 0x1e, 0x9c, 0x1b, 0x73, 0x2f, 0x89, 0x3c, 0x9c,
	0x20, 0xb2, 0x5e, 0xb4, 0xe2, 0x63, 0xf5, 0xc8, 0xfc, 0x15, 0x40, 0xcd, 0xf3, 0x83, 0xea, 0x50,
	0xa2, 0x3d, 0x13, 0x90, 0x12, 0xed, 0xc9, 0x18, 0x71, 0x81, 0x05, 0x31, 0xdb, 0xa8, 0x27, 0xa8,
	0x05, 0xf3, 0xe4, 0x88, 0xa4, 0x82, 0x37, 0x66, 0x14, 0xd3, 0xb5, 0xa2, 0xb7, 0x5d, 0xb5, 0x1a,
	0x19, 0x2d, 0xa9, 0x3f, 0x20, 0x38, 0x16, 0x83, 0xc6, 0xec, 0xc9, 0xfa, 0x2f, 0xd4, 0x6a, 0x64,
	0xb4, 0xc2, 0x2f, 0x61, 0x71, 0xcc, 0x10, 0xda, 0x70, 0x0e, 0x35, 0xbd, 0xd5, 0x13, 0x1d, 0x5a,
	0x7f, 0x61, 0x07, 0x16, 0x7c, 0xb9, 0x4c, 0x85, 0x84, 0xf7, 0x0d, 0x2d, 0x39, 0x9c, 0xc2, 0xeb,
	0x0e, 0x94, 0x1c, 0xa7, 0x66, 0x4b, 0x57, 0xa3, 0x96, 0xad, 0x46, 0xad, 0x6f, 0x6c, 0x35, 0x8a,
	0x4a, 0x82, 0x87, 0x7f, 0x07, 0x0e, 0xa4, 0x46, 0x8f, 0x1a, 0x50, 0x1e, 0xa6, 0x6f, 0x53, 0xf6,
	0x2e, 0x55, 0x9e, 0x2a, 0x91, 0x9d, 0xca, 0x15, 0xcd, 0xec, 0x58, 0xf9, 0xab, 0x44, 0x76, 0x8a,
	0xae, 0xc3, 0x42, 0x8c, 0xb9, 0x68, 0x27, 0x84, 0x73, 0x79, 0x14, 0x66, 0x14, 0x9c, 0x9a, 0x94,
	0xed, 0x6b, 0x11, 0x7a, 0x0c, 0x6a, 0xda, 0xee, 0x0e, 0x70, 0xda, 0x27, 0x66, 0x07, 0x4f, 0x43,
	0x07, 0x52, 0xfd, 0x99, 0xd2, 0x0e, 0x3f, 0x71, 0xc9, 0x7a, 0x20, 0x70, 0x2e, 0xec, 0xd1, 0x2b,
	0x84, 0x39, 0xfc, 0x11, 0x56, 0xc6, 0xd5, 0xce, 0x94, 0xd4, 0x08, 0x66, 0x65, 0x82, 0x99, 0xbd,
	0x55, 0xe3, 0xf0, 0x15, 0x9c, 0x1f, 0xf7, 0x20, 0xf3, 0xf6, 0xf3, 0x89, 0xbc, 0xbd, 0x5c, 0x0c,
	0xec, 0x18, 0x1e, 0x2f, 0x71, 0x6f, 0x02, 0x72, 0x1a, 0x2c, 0x9b, 0xc6, 0xab, 0xed, 0xd1, 0x97,
	0x5a, 0x1f, 0x9d, 0xd6, 0xe8, 0x34, 0x6a, 0x07, 0x1f, 0x78, 0x1a, 0x7d, 0x34, 0x1e, 0xa9, 0x5b,
	0xb0, 0x6a, 0x14, 0x22, 0x19, 0xcb, 0xe9, 0xf1, 0xea, 0xc0, 0x5a, 0x51, 0xf1, 0xa3, 0x53, 0x8b,
	0xdc, 0xde, 0x39, 0x1f, 0x92, 0xdd, 0xe3, 0x09, 0x76, 0x57, 0x8b, 0xec, 0x0a, 0x98, 0x3c, 0x82,
	0x21, 0x2c, 0x9c, 0x96, 0x87, 0x8f, 0x4a, 0x8d, 0x20, 0xbc, 0x09, 0xe0, 0xa5, 0x88, 0x45, 0x16,
	0x8c, 0x90, 0x29, 0xad, 0xeb, 0x50, 0x3b, 0x25, 0xf0, 0x4a, 0xe5, 0x06, 0x54, 0x47, 0x41, 0x99,
	0x66, 0x67, 0x03, 0xea, 0xcf, 0x58, 0x76, 0xfc, 0x7a, 0xe8, 0x30, 0x5d, 0x82, 0x6a, 0xce, 0x98,
	0x68, 0x67, 0x58, 0x0c, 0x8c, 0x7a, 0x45, 0x0a, 0xde, 0x60, 0x31, 0x08, 0x3b, 0x50, 0xdd, 0x3b,
	0xb0, 0x9a, 0xd2, 0x26, 0x63, 0xc2, 0xd9, 0x64, 0x4c, 0xc8, 0xa3, 0x9e, 0x93, 0xee, 0x30, 0xe7,
	0xc4, 0x1e, 0x75, 0x33, 0x45, 0xb7, 0x60, 0x49, 0x0f, 0x29, 0x4b, 0xdb, 0x3d, 0x92, 0x89, 0x81,
	0x3a, 0xed, 0x73, 0x51, 0xdd, 0x89, 0x77, 0xa4, 0x34, 0xfc, 0x37, 0x80, 0xca, 0x73, 0x1a, 0xeb,
	0x82, 0xfc, 0xbf, 0xe3, 0x99, 0xe2, 0xc4, 0x56, 0x37, 0x35, 0x96, 0x32, 0x4e, 0x7f, 0xd6, 0x25,
	0x66, 0x26, 0x52, 0x63, 0x29, 0x4b, 0x58, 0x4f, 0x17, 0x95, 0xc5, 0x48, 0x8d, 0x51, 0x13, 0x2a,
	0x09, 0xeb, 0xd1, 0x43, 0x4a, 0x7a, 0x8d, 0x39, 0xa5, 0xeb, 0xe6, 0x68, 0x15, 0xe6, 0x29, 0x6f,
	0xf7, 0x68, 0xde, 0x98, 0x57, 0xe4, 0xe6, 0x28, 0xdf, 0xa1, 0xb9, 0xac, 0xa6, 0x24, 0xcf, 0x59,
	0xde, 0x28, 0xeb, 0x6a, 0xaa, 0x26, 0xd2, 0x78, 0x4c, 0xd3, 0xb7, 0x8d, 0x8a, 0x06, 0x21, 0xc7,
	0xe8, 0x06, 0x2c, 0xe6, 0x24, 0xc6, 0x82, 0x1e, 0x91, 0xb6, 0x42, 0x58, 0x55, 0x8b, 0x0b, 0x56,
	0xf8, 0x0a, 0x27, 0x24, 0xcc, 0xa0, 0xbe, 0xcf, 0x86, 0xf2, 0x02, 0x39, 0x5b, 0x56, 0xdf, 0xd6,
	0x45, 0xde, 0xde, 0xac, 0xc8, 0xe5, 0xa9, 0xb2, 0x7e, 0x20, 0xb0, 0xd0, 0x85, 0x9f, 0xcb, 0xde,
	0xcf, 0x7a, 0x7c, 0x5f, 0xef, 0x37, 0x8e, 0xcc, 0xcb, 0xed, 0x5f, 0xa0, 0xea, 0xec, 0xa2, 0x2b,
	0x00, 0x87, 0x34, 0x26, 0xfc, 0x98, 0x0b, 0x92, 0x98, 0x04, 0xf1, 0x24, 0x2e, 0x18, 0x32, 0x40,
	0xb3, 0x26, 0x18, 0xeb, 0x50, 0xc5, 0x47, 0x98, 0xc6, 0xb8, 0x13, 0xeb, 0x28, 0xcd, 0x46, 0x23,
	0x01, 0xba, 0x0c, 0x90, 0x48, 0xf3, 0xa4, 0xd7, 0x66, 0xa9, 0x0a, 0x58, 0x35, 0xaa, 0x1a, 0xc9,
	0xeb, 0x34, 0xfc, 0x27, 0x80, 0xa5, 0xef, 0x88, 0xca, 0xa2, 0x33, 0xee, 0x5a, 0x0b, 0xca, 0x47,
	0xda, 0x90, 0x42, 0xe7, 0x77, 0x24, 0xc6, 0x81, 0xea, 0x48, 0xac, 0x12, 0xfa, 0x0c, 0x2a, 0x59,
	0x8c, 0xc5, 0x21, 0xcb, 0x13, 0x73, 0x75, 0x8e, 0x6e, 0xe7, 0x37, 0x66, 0x41, 0xf7, 0x30, 0x56,
	0x4d, 0x36, 0x62, 0x0e, 0xeb, 0xfb, 0x1a, 0xb1, 0x02, 0x29, 0x6f, 0xc3, 0xff, 0x0c, 0xa0, 0xe6,
	0x21, 0x92, 0xb7, 0xbc, 0xc0, 0xee, 0x96, 0x17, 0xb8, 0x2f, 0x25, 0x7c, 0x80, 0x6d, 0x0b, 0xc8,
	0x07, 0x58, 0x66, 0x6a, 0x67, 0x48, 0x63, 0x61, 0x2e, 0x5a, 0x3d, 0x91, 0x7b, 0xdb, 0x67, 0x6d,
	0xcb, 0xda, 0xec, 0x6d, 0x9f, 0x19, 0xe3, 0xb2, 0xb8, 0x30, 0xae, 0xce, 0x42, 0x35, 0x2a, 0x31,
	0x2e, 0x83, 0x87, 0xf3, 0xee, 0x40, 0x9d, 0x81, 0x6a, 0xa4, 0xc6, 0xe1, 0x03, 0x58, 0xf0, 0xc9,
	0xba, 0x13, 0x18, 0x8c, 0x9f, 0x40, 0x75, 0xda, 0xcc, 0xa9, 0x94, 0xe3, 0xf0, 0xb7, 0x00, 0x6a,
	0x7b, 0xac, 0xcf, 0x6d, 0x4d, 0x59, 0x87, 0xaa, 0xd4, 0xe5, 0x19, 0xee, 0xda, 0x8f, 0x47, 0x02,
	0x53, 0xe6, 0x4a, 0xae, 0x3d, 0xdb, 0x84, 0xf9, 0x5e, 0x4e, 0x8f, 0x48, 0xae, 0xf8, 0xd4, 0xb7,
	0x2e, 0xd8, 0xf8, 0x3e, 0x63, 0xa9, 0xc0, 0x34, 0x25, 0xf9, 0x8e, 0x5a, 0x8e, 0x8c, 0x1a, 0x5a,
	0x83, 0xf9, 0x43, 0x16, 0xc7, 0xec, 0x9d, 0x62, 0x59, 0x89, 0xcc, 0x4c, 0x96, 0xd3, 0x88, 0xe0,
	0x9e, 0x57, 0xd9, 0xbc, 0xf2, 0xa7, 0xc6, 0x5b, 0x7f, 0x54, 0xa0, 0xbc, 0xaf, 0x83, 0x82, 0x1e,
	0x41, 0xd9, 0x54, 0x4d, 0x34, 0x3a, 0x19, 0xe3, 0x75, 0xb4, 0xb9, 0x62, 0xb1, 0xec, 0xc8, 0xfc,
	0x32, 0x41, 0xbb, 0x1b, 0xa0, 0x2f, 0x00, 0x5e, 0x0e, 0x3b, 0xa4, 0xcb, 0xd2, 0x43, 0xda, 0x47,
	0x6b, 0x13, 0x8d, 0xcc, 0xae, 0x7c, 0x11, 0x4e, 0xfd, 0x7a, 0x03, 0x4a, 0x7b, 0x07, 0x68, 0x74,
	0x94, 0x5d, 0x35, 0x6e, 0x9e, 0x77, 0x32, 0x5b, 0x3c, 0xef, 0x06, 0x68, 0x1b, 0x66, 0xe5, 0xee,
	0xa2, 0x51, 0x0e, 0x7b, 0x9b, 0x3d, 0xd5, 0xc9, 0x03, 0x98, 0xd7, 0xc7, 0xfc, 0x14, 0x78, 0xc5,
	0x7a, 0xa0, 0xf3, 0x78, 0x56, 0xee, 0xa2, 0xe7, 0xcd, 0xdb, 0xd4, 0xd3, 0xbc, 0xe9, 0x07, 0xe5,
	0x07, 0x78, 0xf3, 0x5f, 0xa8, 0xdb, 0x30, 0xa7, 0x9e, 0x7f, 0x53, 0x3f, 0x5b, 0x2e, 0x3e, 0x13,
	0xe5, 0x57, 0x4f, 0x5c, 0xc3, 0x2f, 0x9f, 0x04, 0x53, 0xbf, 0xbd, 0x78, 0xf2, 0x03, 0x42, 0x5a,
	0x78, 0x05, 0xf5, 0xf1, 0x8b, 0x1e, 0x5d, 0x99, 0xda, 0x01, 0x68, 0xe6, 0xeb, 0x53, 0xd7, 0xa5,
	0xbd, 0x17, 0xae, 0x5b, 0x57, 0xf7, 0x3e, 0x5a, 0x9f, 0xd2, 0x03, 0x6a, 0x5b, 0xcd, 0x29, 0xab,
	0xd2, 0xd2, 0xae, 0xe3, 0x26, 0x2f, 0x7e, 0x74, 0xe9, 0xe4, 0xb6, 0x4b, 0xdb, 0xb9, 0x78, 0xf2,
	0xa2, 0x34, 0xf3, 0x08, 0x2a, 0xf6, 0x21, 0x3b, 0x75, 0x7f, 0xd6, 0x4e, 0x78, 0xf3, 0xea, 0x96,
	0xb6, 0x6c, 0x9e, 0x8e, 0xde, 0xc9, 0x18, 0x7f, 0xf8, 0x36, 0x57, 0x27, 0x17, 0x74, 0xdf, 0x38,
	0xa7, 0x37, 0xc0, 0x7b, 0xdd, 0xf8, 0xcc, 0x97, 0x8b, 0xe2, 0x2c, 0x3e, 0x0e, 0x67, 0x7e, 0x2f,
	0x05, 0xe8, 0x3e, 0xcc, 0x2a, 0xc2, 0xde, 0xdb, 0xd1, 0x63, 0x8a, 0x0a, 0x52, 0xf7, 0xd9, 0x43,
	0x28, 0xdb, 0x12, 0x37, 0x8d, 0xe6, 0xea, 0x64, 0x1d, 0xce, 0xe2, 0xe3, 0xa7, 0x2f, 0x61, 0xa9,
	0xcb, 0x12, 0xb7, 0x86, 0x33, 0xfa, 0x14, 0x4c, 0x6d, 0xf8, 0x2a, 0xa3, 0x6f, 0x82, 0x1f, 0xee,
	0xf4, 0xa9, 0x18, 0x0c, 0x3b, 0x32, 0xe3, 0x37, 0x05, 0x8e, 0x19, 0xdf, 0xd0, 0x17, 0x1f, 0xd7,
	0xb3, 0x4d, 0x9c, 0x51, 0xfb, 0x17, 0x51, 0x67, 0x5e, 0xf9, 0xbc, 0xf7, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xea, 0x65, 0x81, 0x0d, 0x3c, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConn
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MachineClient is the client API for Machine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MachineClient interface {
	CopyOut(ctx context.Context, in *CopyOutRequest, opts ...grpc.CallOption) (Machine_CopyOutClient, error)
	Kubeconfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Machine_KubeconfigClient, error)
	LS(ctx context.Context, in *LSRequest, opts ...grpc.CallOption) (Machine_LSClient, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (Machine_LogsClient, error)
	Mounts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MountsReply, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Machine_ReadClient, error)
	Reboot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RebootReply, error)
	Reset(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ResetReply, error)
	ServiceList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ServiceListReply, error)
	ServiceRestart(ctx context.Context, in *ServiceRestartRequest, opts ...grpc.CallOption) (*ServiceRestartReply, error)
	ServiceStart(ctx context.Context, in *ServiceStartRequest, opts ...grpc.CallOption) (*ServiceStartReply, error)
	ServiceStop(ctx context.Context, in *ServiceStopRequest, opts ...grpc.CallOption) (*ServiceStopReply, error)
	Shutdown(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ShutdownReply, error)
	Upgrade(ctx context.Context, in *UpgradeRequest, opts ...grpc.CallOption) (*UpgradeReply, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error)
	Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionReply, error)
}

type machineClient struct {
	cc *grpc.ClientConn
}

func NewMachineClient(cc *grpc.ClientConn) MachineClient {
	return &machineClient{cc}
}

func (c *machineClient) CopyOut(ctx context.Context, in *CopyOutRequest, opts ...grpc.CallOption) (Machine_CopyOutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Machine_serviceDesc.Streams[0], "/machine.Machine/CopyOut", opts...)
	if err != nil {
		return nil, err
	}
	x := &machineCopyOutClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Machine_CopyOutClient interface {
	Recv() (*common.DataResponse, error)
	grpc.ClientStream
}

type machineCopyOutClient struct {
	grpc.ClientStream
}

func (x *machineCopyOutClient) Recv() (*common.DataResponse, error) {
	m := new(common.DataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *machineClient) Kubeconfig(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Machine_KubeconfigClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Machine_serviceDesc.Streams[1], "/machine.Machine/Kubeconfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &machineKubeconfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Machine_KubeconfigClient interface {
	Recv() (*common.DataResponse, error)
	grpc.ClientStream
}

type machineKubeconfigClient struct {
	grpc.ClientStream
}

func (x *machineKubeconfigClient) Recv() (*common.DataResponse, error) {
	m := new(common.DataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *machineClient) LS(ctx context.Context, in *LSRequest, opts ...grpc.CallOption) (Machine_LSClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Machine_serviceDesc.Streams[2], "/machine.Machine/LS", opts...)
	if err != nil {
		return nil, err
	}
	x := &machineLSClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Machine_LSClient interface {
	Recv() (*FileInfo, error)
	grpc.ClientStream
}

type machineLSClient struct {
	grpc.ClientStream
}

func (x *machineLSClient) Recv() (*FileInfo, error) {
	m := new(FileInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *machineClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (Machine_LogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Machine_serviceDesc.Streams[3], "/machine.Machine/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &machineLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Machine_LogsClient interface {
	Recv() (*common.DataResponse, error)
	grpc.ClientStream
}

type machineLogsClient struct {
	grpc.ClientStream
}

func (x *machineLogsClient) Recv() (*common.DataResponse, error) {
	m := new(common.DataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *machineClient) Mounts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MountsReply, error) {
	out := new(MountsReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/Mounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (Machine_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Machine_serviceDesc.Streams[4], "/machine.Machine/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &machineReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Machine_ReadClient interface {
	Recv() (*common.DataResponse, error)
	grpc.ClientStream
}

type machineReadClient struct {
	grpc.ClientStream
}

func (x *machineReadClient) Recv() (*common.DataResponse, error) {
	m := new(common.DataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *machineClient) Reboot(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RebootReply, error) {
	out := new(RebootReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/Reboot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) Reset(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ResetReply, error) {
	out := new(ResetReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) ServiceList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ServiceListReply, error) {
	out := new(ServiceListReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/ServiceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) ServiceRestart(ctx context.Context, in *ServiceRestartRequest, opts ...grpc.CallOption) (*ServiceRestartReply, error) {
	out := new(ServiceRestartReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/ServiceRestart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) ServiceStart(ctx context.Context, in *ServiceStartRequest, opts ...grpc.CallOption) (*ServiceStartReply, error) {
	out := new(ServiceStartReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/ServiceStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) ServiceStop(ctx context.Context, in *ServiceStopRequest, opts ...grpc.CallOption) (*ServiceStopReply, error) {
	out := new(ServiceStopReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/ServiceStop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) Shutdown(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ShutdownReply, error) {
	out := new(ShutdownReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) Upgrade(ctx context.Context, in *UpgradeRequest, opts ...grpc.CallOption) (*UpgradeReply, error) {
	out := new(UpgradeReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/Upgrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *machineClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error) {
	out := new(StartReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *machineClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error) {
	out := new(StopReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineClient) Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionReply, error) {
	out := new(VersionReply)
	err := c.cc.Invoke(ctx, "/machine.Machine/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineServer is the server API for Machine service.
type MachineServer interface {
	CopyOut(*CopyOutRequest, Machine_CopyOutServer) error
	Kubeconfig(*empty.Empty, Machine_KubeconfigServer) error
	LS(*LSRequest, Machine_LSServer) error
	Logs(*LogsRequest, Machine_LogsServer) error
	Mounts(context.Context, *empty.Empty) (*MountsReply, error)
	Read(*ReadRequest, Machine_ReadServer) error
	Reboot(context.Context, *empty.Empty) (*RebootReply, error)
	Reset(context.Context, *empty.Empty) (*ResetReply, error)
	ServiceList(context.Context, *empty.Empty) (*ServiceListReply, error)
	ServiceRestart(context.Context, *ServiceRestartRequest) (*ServiceRestartReply, error)
	ServiceStart(context.Context, *ServiceStartRequest) (*ServiceStartReply, error)
	ServiceStop(context.Context, *ServiceStopRequest) (*ServiceStopReply, error)
	Shutdown(context.Context, *empty.Empty) (*ShutdownReply, error)
	Upgrade(context.Context, *UpgradeRequest) (*UpgradeReply, error)
	Start(context.Context, *StartRequest) (*StartReply, error)
	Stop(context.Context, *StopRequest) (*StopReply, error)
	Version(context.Context, *empty.Empty) (*VersionReply, error)
}

func RegisterMachineServer(s *grpc.Server, srv MachineServer) {
	s.RegisterService(&_Machine_serviceDesc, srv)
}

func _Machine_CopyOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CopyOutRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServer).CopyOut(m, &machineCopyOutServer{stream})
}

type Machine_CopyOutServer interface {
	Send(*common.DataResponse) error
	grpc.ServerStream
}

type machineCopyOutServer struct {
	grpc.ServerStream
}

func (x *machineCopyOutServer) Send(m *common.DataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Machine_Kubeconfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServer).Kubeconfig(m, &machineKubeconfigServer{stream})
}

type Machine_KubeconfigServer interface {
	Send(*common.DataResponse) error
	grpc.ServerStream
}

type machineKubeconfigServer struct {
	grpc.ServerStream
}

func (x *machineKubeconfigServer) Send(m *common.DataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Machine_LS_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LSRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServer).LS(m, &machineLSServer{stream})
}

type Machine_LSServer interface {
	Send(*FileInfo) error
	grpc.ServerStream
}

type machineLSServer struct {
	grpc.ServerStream
}

func (x *machineLSServer) Send(m *FileInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _Machine_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServer).Logs(m, &machineLogsServer{stream})
}

type Machine_LogsServer interface {
	Send(*common.DataResponse) error
	grpc.ServerStream
}

type machineLogsServer struct {
	grpc.ServerStream
}

func (x *machineLogsServer) Send(m *common.DataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Machine_Mounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Mounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/Mounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Mounts(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServer).Read(m, &machineReadServer{stream})
}

type Machine_ReadServer interface {
	Send(*common.DataResponse) error
	grpc.ServerStream
}

type machineReadServer struct {
	grpc.ServerStream
}

func (x *machineReadServer) Send(m *common.DataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Machine_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/Reboot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Reboot(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Reset(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_ServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).ServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/ServiceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).ServiceList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_ServiceRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).ServiceRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/ServiceRestart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).ServiceRestart(ctx, req.(*ServiceRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_ServiceStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).ServiceStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/ServiceStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).ServiceStart(ctx, req.(*ServiceStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_ServiceStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).ServiceStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/ServiceStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).ServiceStop(ctx, req.(*ServiceStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Shutdown(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_Upgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Upgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/Upgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Upgrade(ctx, req.(*UpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Machine_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/machine.Machine/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineServer).Version(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Machine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "machine.Machine",
	HandlerType: (*MachineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mounts",
			Handler:    _Machine_Mounts_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _Machine_Reboot_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Machine_Reset_Handler,
		},
		{
			MethodName: "ServiceList",
			Handler:    _Machine_ServiceList_Handler,
		},
		{
			MethodName: "ServiceRestart",
			Handler:    _Machine_ServiceRestart_Handler,
		},
		{
			MethodName: "ServiceStart",
			Handler:    _Machine_ServiceStart_Handler,
		},
		{
			MethodName: "ServiceStop",
			Handler:    _Machine_ServiceStop_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Machine_Shutdown_Handler,
		},
		{
			MethodName: "Upgrade",
			Handler:    _Machine_Upgrade_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Machine_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Machine_Stop_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Machine_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CopyOut",
			Handler:       _Machine_CopyOut_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Kubeconfig",
			Handler:       _Machine_Kubeconfig_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LS",
			Handler:       _Machine_LS_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _Machine_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _Machine_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "machine/machine.proto",
}
