// Code generated by "stringer -type=PeerState -linecomment"; DO NOT EDIT.

package kubespan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PeerStateUnknown-0]
	_ = x[PeerStateUp-1]
	_ = x[PeerStateDown-2]
}

const _PeerState_name = "unknownupdown"

var _PeerState_index = [...]uint8{0, 7, 9, 13}

func (i PeerState) String() string {
	if i < 0 || i >= PeerState(len(_PeerState_index)-1) {
		return "PeerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PeerState_name[_PeerState_index[i]:_PeerState_index[i+1]]
}
