name: Promote E2E

on:
  issue_comment:
    types: [created]

jobs:
  check_ok_to_test:
    runs-on: ubuntu-latest
    name: "Check comments for /e2e"
    steps:
      - name: Check for test slash command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: "e2e"
          permission-level: "write"
          reaction: "true"
          reaction-type: "rocket"

      - name: Checkout repo
        uses: actions/checkout@master

      - name: Apply needs-e2e Label
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: label needs-e2e

      - name: Retrigger drone
        run: |
          ## Fetch PR number and github status URL
          PULL_NUMBER=$(jq -r .issue.number "$GITHUB_EVENT_PATH")
          PR_INFO=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PULL_NUMBER")
          STATUS_URL=$(echo $PR_INFO | jq -r .statuses_url)

          ## Discover previous drone build number and send it a post to promote
          DRONE_BUILD_URL=$(curl -s $STATUS_URL | jq -r '[.[] | select(.context == "continuous-integration/drone/pr")][0].target_url')
          DRONE_BUILD_NUM=${DRONE_BUILD_URL##*/}

          docker run  -e "DRONE_SERVER=$DRONE_SERVER" -e "DRONE_TOKEN=$DRONE_TOKEN" drone/cli:1.2.1 build promote $GITHUB_REPOSITORY $DRONE_BUILD_NUM e2e
        env:
          GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
          DRONE_SERVER: "https://ci.dev.talos-systems.io"
          DRONE_TOKEN: ${{ secrets.DRONE_TOKEN }}